- platform: template
  sensors:
    master_bedroom_baseboard_heat_on:
        friendly_name: 'Master Bedroom Baseboard Heat On'
        device_class: heat
        value_template: '{{ states.sensor.master_bedroom_temperature_change_rate.state | float > 0.8 }}'

- platform: bayesian
  name: 'Master Bedroom Bayesian Baseboard Heat Sensor'
  prior: 0.7
  probability_threshold: 0.85
  observations:
    - entity_id: sensor.master_bedroom_temperature_change_rate
      prob_given_true: 0.7
      platform: 'numeric_state'
      above: 1
    - entity_id: sensor.sn3_temperature
      prob_given_true: 0.9
      platform: 'numeric_state'
      below: 60
    - entity_id: sensor.weather_temperature
      prob_given_true: 0.55
      platform: numeric_state
      below: 50
    - entity_id: sun.sun
      prob_given_true: 0.7
      prob_given_false: 0.4
      platform: state
      to_state: 'below_horizon'
    - entity_id: sensor.master_bedroom_compensated_temperature_change_rate
      prob_given_true: 0.95
      prob_given_false: 0.2
      platform: numeric_state
      above: 2
    - entity_id: sensor.master_bedroom_compensated_temperature_change_rate
      prob_given_true: 0.7
      prob_given_false: 0.1
      platform: numeric_state
      above: 1
