- platform: template
  sensors:
    average_cooling_required:
      friendly_name: 'Inside: Cooling Required'
      device_class: heat
      entity_id:
        - sensor.indoor_cooling_setpoint_temperature_delta
        - input_number.cooling_threshold
      value_template: >
        {% if (states.sensor.indoor_cooling_setpoint_temperature_delta.state | float) > (states.input_number.cooling_threshold.state | float) %}
         True
        {% elif ((states.binary_sensor.average_cooling_required.state) == "on") and (states.sensor.indoor_cooling_setpoint_temperature_delta.state | float) > (-1 * (states.input_number.cooling_threshold.state | float) ) %}
         True
        {% else %}
         False
        {% endif %}

- platform: trend
  sensors:
    master_bedroom_temperature_trend:
      friendly_name: "Master Bedroom Temperature Trend"
      entity_id: sensor.master_bedroom_temperature
      max_samples: 100
      sample_duration: 900
      min_gradient: 0.000138
      device_class: heat
    office_temperature_trend:
      friendly_name: "Office Temperature Trend"
      entity_id: sensor.office_temperature
      max_samples: 100
      sample_duration: 900
      min_gradient: 0.000138
      device_class: heat
    bike_room_temperature_trend:
      friendly_name: "Bike Room Temperature Trend"
      entity_id: sensor.bike_room_temperature
      max_samples: 100
      sample_duration: 900
      min_gradient: 0.000138
      device_class: heat
    living_room_temperature_trend:
      friendly_name: "Living Room Temperature Trend"
      entity_id: sensor.living_room_temperature
      max_samples: 100
      sample_duration: 900
      min_gradient: 0.000138
      device_class: heat
    bonus_room_temperature_trend:
      friendly_name: "Bonus Room Temperature Trend"
      entity_id: sensor.bonus_room_temperature
      max_samples: 100
      sample_duration: 900
      min_gradient: 0.000138
      device_class: heat
    outdoor_temperature_trend:
      friendly_name: "Outdoor Temperature Trend"
      entity_id: sensor.outdoor_temperature
      max_samples: 5
      sample_duration: 3600
      min_gradient: 0.000138
      device_class: heat
