- platform: template
  sensors:
    media_center_is_playing:
      friendly_name: "Media Center: Is Playing"
      value_template: >
        {% if is_state('input_select.harmony_activity_select', 'Off') %}
          False
        {% elif is_state('input_select.harmony_activity_select', 'Watch Chromecast') and is_state('media_player.living_room_chromecast','playing') %}
          True
        {% elif is_state('input_select.harmony_activity_select', 'Watch PC') and is_state('media_player.master','playing') %}
          True
        {% elif is_state('media_player.living_room_chromecast','playing') and is_state('switch.hdmi_0', 'on') %}
          True
        {% else %}
          False
        {% endif %}
