- platform: workday
  country: US
  province: WA

- platform: template
  sensors:
    ok_to_open_window:
      friendly_name: 'OK to Open Window'
      value_template: >
        {% if (states('sensor.sn2_temperature') > states('sensor.weather_temperature')) and ( states('sensor.sn2_temperature') | float > (float(states('input_number.cooling_setpoint')) + 2) ) %}
          True
        {% elif (states('sensor.sn2_temperature') < states('sensor.weather_temperature')) and ( states('sensor.sn2_temperature') | float < (float(states('input_number.cooling_setpoint')) - 2) ) %}
          True
        {% else %}
          False
        {% endif %}

- platform: bayesian
  name: 'Everyone in Bed'
  prior: 0.25
  probability_threshold: 0.95
  observations:
    - entity_id: 'sensor.sn2_motion'
      prob_given_true: 0.7
      prob_given_false: 0.3
      platform: 'state'
      to_state: 'off'
    - entity_id: 'sensor.office_motion'
      prob_given_true: 0.7
      prob_given_false: 0.3
      platform: 'state'
      to_state: 'off'
    - entity_id: 'sensor.sn3_motion'
      prob_given_true: 0.4
      prob_given_false: 0.3
      platform: 'state'
      to_state: 'off'
    - entity_id: 'sensor.bike_room_motion'
      prob_given_true: 0.7
      prob_given_false: 0.2
      platform: 'state'
      to_state: 'off'
    - entity_id: 'sun.sun'
      prob_given_true: 0.7
      prob_given_false: 0.3
      platform: 'state'
      to_state: 'below_horizon'
    - entity_id: 'group.indoor_lights'
      prob_given_true: 0.7
      prob_given_false: 0.3
      platform: 'state'
      to_state: 'off'
    - entity_id: 'group.guests'
      prob_given_true: 0.6
      platform: 'state'
      to_state: 'not_home'
    - entity_id: 'binary_sensor.everybody_home'
      prob_given_true: 0.8
      prob_given_false: 0.05
      platform: 'state'
      to_state: 'on'
