- platform: trend
  sensors:
    master_bedroom_temperature_trend:
      friendly_name: "Master Bedroom Temperature Trend"
      entity_id: sensor.master_bedroom_temperature
      max_samples: 100
      sample_duration: 900
      min_gradient: 0.000138
      device_class: heat
    office_temperature_trend:
      friendly_name: "Office Temperature Trend"
      entity_id: sensor.office_temperature
      max_samples: 100
      sample_duration: 900
      min_gradient: 0.000138
      device_class: heat
    bike_room_temperature_trend:
      friendly_name: "Bike Room Temperature Trend"
      entity_id: sensor.bike_room_temperature
      max_samples: 100
      sample_duration: 900
      min_gradient: 0.000138
      device_class: heat
    living_room_temperature_trend:
      friendly_name: "Living Room Temperature Trend"
      entity_id: sensor.living_room_temperature
      max_samples: 100
      sample_duration: 900
      min_gradient: 0.000138
      device_class: heat
    bonus_room_temperature_trend:
      friendly_name: "Bonus Room Temperature Trend"
      entity_id: sensor.bonus_room_temperature
      max_samples: 100
      sample_duration: 900
      min_gradient: 0.000138
      device_class: heat
    outdoor_temperature_trend:
      friendly_name: "Outdoor Temperature Trend"
      entity_id: sensor.outdoor_temperature
      max_samples: 10
      sample_duration: 1800
      min_gradient: 0.000138
      device_class: heat
