- platform: workday
  country: US
  province: WA

- platform: template
  sensors:
    ok_to_open_window:
      friendly_name: 'OK to Open Window'
      value_template: >
        {% if (states('sensor.living_room_temperature') | float > state_attr('weather.home_weather', 'temperature') | float) and ( states('sensor.living_room_temperature') | float > (float(states('input_number.cooling_setpoint')) + 2) ) %}
          True
        {% elif (states('sensor.living_room_temperature') | float < state_attr('weather.home_weather', 'temperature') | float) and ( states('sensor.living_room_temperature') | float < (float(states('input_number.cooling_setpoint')) - 2) ) %}
          True
        {% else %}
          False
        {% endif %}
