- platform: generic_thermostat
  name: Living Room Fan
  heater: switch.living_room_fan
  target_sensor: sensor.living_room_temperature
  min_temp: 60
  max_temp: 75
  ac_mode: True
  keep_alive:
    minutes: 15
  min_cycle_duration:
    minutes: 15
  initial_operation_mode: 'off'
