homeassistant:
  name: !secret home_name
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: America/Los_Angeles
  customize: !include_dir_merge_named customize
  auth_providers:
  - type: homeassistant
  - type: legacy_api_password
  packages: !include_dir_named packages
frontend:
config:
http:
  api_password: !secret http_password
  server_port: !secret server_port
  base_url: !secret base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 5
updater:
  include_used_components: true
discovery:
  ignore:
    - roku
sun:
map:

# Log and history configuration
recorder:
  purge_keep_days: 7
  purge_interval: 1
  exclude:
    entities:
      - sensor.uptime
      - automation.hass_reset_mqtt_timeout
      - sensor.bedroom_lights_toggle_randomizer
      - sensor.kitchen_lights_toggle_randomizer
      - sensor.living_room_tv_toggle_randomizer
      - sensor.mqtt_broker_uptime
      - sensor.office_uptime
      - sensor.master_bedroom_uptime
      - sensor.living_room_uptime
      - sensor.bonus_room_uptime
      - sensor.bike_room_uptime
      - sensor.time
      - sensor.date
      - sensor.3d_printer_job_finish_time
      - sensor.3d_printer_job_remaining_time_seconds
      - sensor.3d_printer_job_time_remaining_trend_filtered
      - sensor.3d_printer_job_time_remaining_trend_raw
      - sensor.solar_elevation
history:
  exclude:
    domains:
      - automation
      - group

logbook:
  exclude:
    entities:
      - binary_sensor.office_status
      - binary_sensor.living_room_status
      - binary_sensor.master_bedroom_status
      - binary_sensor.bonus_room_status
      - binary_sensor.bike_room_status
      - sensor.average_load_5m
      - group.office_sensor
      - group.living_room_sensor
      - group.sensor_node_3_card
      - group.sensor_node_4_card
      - group.sensor_node_5_card
      - group.bike_room_sensor
logger:
  default: warning

mqtt:
  discovery: true
  broker: 192.168.1.20
  port: 1883
  client_id: hassio
  username: !secret mqtt_username
  password: !secret mqtt_password
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

zha:
  usb_path: "/dev/ttyUSB1"
  database_path: /config/zigbee.db

#Single-file includes.
device_tracker: !include device_tracker.yaml
history_graph: !include history_graph.yaml

#Split all the major components into their own directories.
group: !include_dir_merge_named group

#Dir_Merge_Lists must contain lists in each file.
scene: !include_dir_merge_list scene
zone: !include_dir_merge_list zone
notify: !include_dir_merge_list notify
