homeassistant:
  name: !secret home_name
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: America/Los_Angeles
  customize: !include customize.yaml
  auth_providers:
  - type: homeassistant
  packages: !include_dir_named packages
http:
  server_port: !secret server_port
  base_url: !secret base_url
updater:
  include_used_components: true
discovery:
stream:
default_config:

# Log and history configuration
recorder:
  db_url: !secret externaldb_string
  purge_keep_days: 14
  commit_interval: 2
  exclude:
    entities:
      - sensor.uptime
      - automation.hass_reset_mqtt_timeout
      - sensor.time
      - sensor.date
      - sensor.3d_printer_job_finish_time
      - sensor.3d_printer_job_remaining_time_seconds
      - sensor.3d_printer_job_time_remaining_trend_filtered
      - sensor.3d_printer_job_time_remaining_trend_raw
      - sensor.solar_elevation
      - sensor.mqtt_broker_uptime
      - timer.3d_printer_job_remaining_time
      - sensor.average_light_level_raw
history:
  exclude:
    domains:
      - automation
logbook:

logger:
  default: warning

mqtt:
  discovery: true
  broker: 192.168.1.50
  port: 1883
  client_id: hassio
  username: !secret mqtt_username_new
  password: !secret mqtt_password
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

hacs:
  token: !secret github_personal_access_token

#Split all the major components into their own directories.
group: !include_dir_merge_named group

#Dir_Merge_Lists must contain lists in each file.
zone: !include_dir_merge_list zone
notify: !include_dir_merge_list notify
