- platform: mqtt
  name: "Office Fan"
  state_topic: "stat/officefan/RESULT"
  speed_state_topic: "stat/officefan/RESULT"
  state_value_template: "{% if value_json.FanSpeed == 0 -%}0{%- elif value_json.FanSpeed > 0 -%}2{%- endif %}"
  speed_value_template: "{{ value_json.FanSpeed }}"
  availability_topic: tele/officefan/LWT
  payload_available: Online
  payload_not_available: Offline
  speed_command_topic: "cmnd/officefan/FanSpeed"
  payload_low_speed: "1"
  payload_medium_speed: "2"
  payload_high_speed: "3"
  command_topic: "cmnd/officefan/FanSpeed"
  payload_off: "0"
  payload_on: "2"
  speeds:
    - low
    - medium
    - high

- platform: mqtt
  name: "Bonus Room Fan"
  state_topic: "stat/bonusroomfan/RESULT"
  speed_state_topic: "stat/bonusroomfan/RESULT"
  state_value_template: "{% if value_json.FanSpeed == 0 -%}0{%- elif value_json.FanSpeed > 0 -%}2{%- endif %}"
  speed_value_template: "{{ value_json.FanSpeed }}"
  availability_topic: tele/bonusroomfan/LWT
  payload_available: Online
  payload_not_available: Offline
  speed_command_topic: "cmnd/bonusroomfan/FanSpeed"
  payload_low_speed: "1"
  payload_medium_speed: "2"
  payload_high_speed: "3"
  command_topic: "cmnd/bonusroomfan/FanSpeed"
  payload_off: "0"
  payload_on: "2"
  speeds:
    - low
    - medium
    - high
