- platform: mqtt_json
  name: "SN2 LED"
  state_topic: "bruh/livingroom"
  command_topic: "bruh/livingroom/set"
  brightness: true
  flash: true
  rgb: true
  effect: true
  effect_list:
    - breathe
    - pir_light
    - blink
  optimistic: false
  qos: 1

- platform: mqtt_json
  name: "SN4 LED"
  state_topic: "bruh/bonusroom"
  command_topic: "bruh/bonusroom/set"
  brightness: true
  flash: true
  rgb: true
  effect: true
  effect_list:
    - breathe
    - pir_light
    - blink
  optimistic: false
  qos: 1

#- platform: mqtt_json
#  name: "SN5 LED"
#  state_topic: "bruh/sensornode5"
#  command_topic: "bruh/sensornode5/set"
#  brightness: true
#  flash: true
#  rgb: true
#  effect: true
#  effect_list:
#    - breathe
#    - pir_light
#    - blink
#  optimistic: false
#  qos: 1

- platform: mqtt_json
  name: "Bike Room LED"
  state_topic: "bruh/bikeroom"
  command_topic: "bruh/bikeroom/set"
  brightness: true
  flash: true
  rgb: true
  effect: true
  effect_list:
    - breathe
    - pir_light
    - blink
  optimistic: false
  qos: 1
