- platform: mqtt
  name: "Seedling Fan"
  state_topic: "stat/sonoff-gardeningfan/POWER"
  command_topic: "cmnd/sonoff-gardeningfan/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "Living Room Fan"
  state_topic: "stat/sonoff-livingroomfan/POWER"
  command_topic: "cmnd/sonoff-livingroomfan/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

#- platform: tplink
#  host: 192.168.1.52
#  name: 'Bonus Room Heater'
