#DOOR SENSORS:
#1: Front door
#2: Back door
#3: Master Bedroom
#4: Dog Food Container
#5: Bike Room Right Door

- platform: rflink
  device_defaults:
    fire_event: true
  devices:
    ev1527_0236bc_01:
      name: Front Door Sensor
    ev1527_0ea981_02:
      name: Back Door Sensor
    ev1527_08b1a2_03:
      name: Master Bedroom Door Sensor
    ev1527_02fabc_04:
      name: Dog Food Container Sensor
    ev1527_025c62_05:
      name: Bike Room Door Sensor
