environment_view:
  name: 'Network Health'
  view: yes
  icon: mdi:weather-cloudy
  entities:
    - group.environment_outside
    - group.office_card
    - group.living_room_card
    - group.master_bedroom_card
    - group.bonus_room_card
    - group.bike_room_sensor
    - group.temperature
    - group.fan_control
    - group.misc_env

temperature:
  name: 'Temperature'
  entities:
    - sensor.average_indoor_temperature
    - sensor.average_indoor_temperature_rate
    - sensor.weather_temperature
    - sensor.outdoor_temperature_rate
    - sensor.indoor_outdoor_temperature_delta

fan_control:
  name: 'Living Room Fan Control'
  entities:
    - climate.living_room_fan
    - sensor.living_room_outdoor_temperature_delta
    - history_graph.living_room_temperature_history

misc_env:
  name: "Miscellaneous"
  entities:
    - sensor.average_humidity
    - sensor.average_light_level

environment_outside:
  name: 'Environment'
  entities:
    - weather.home_weather
    - sun.sun
