environment_view:
  name: 'Network Health'
  view: yes
  icon: mdi:weather-cloudy
  entities:
    - weather.home_weather
    - group.office_card
    - group.living_room_card
    - group.master_bedroom_card
    - group.bonus_room_card
    - group.bike_room_sensor
    - group.temperature
    - group.fan_control
    - group.ceiling_fans
    - group.misc_env
    - history_graph.living_room_temperature_history
    - history_graph.temperature_deltas
    - history_graph.temperature_rates

temperature:
  name: 'Temperature'
  entities:
    - sensor.weather_temperature
    - sensor.outdoor_temperature_rate

fan_control:
  name: 'Living Room Fan Control'
  entities:
    - climate.living_room_fan
    - sensor.living_room_outdoor_temperature_delta

misc_env:
  name: "Miscellaneous"
  entities:
    - sensor.us_air_quality_index
    - sensor.us_air_pollution_level
    - sensor.allergy_index_today
    - sensor.allergy_average_forecasted
    - sensor.disease_average_forecasted

ceiling_fans:
  name: 'Ceiling Fans'
  entities:
    - fan.office_fan
    - climate.office_fan
    - fan.bonus_room_fan
    - climate.bonus_room_fan
