environment_view:
  name: 'Network Health'
  view: yes
  icon: mdi:weather-cloudy
  entities:
    - group.environment_outside
    - group.office_card
    - group.living_room_card
    - group.master_bedroom_card
    - group.bonus_room_card
    - group.bike_room_sensor
    - group.temperature
    - group.fan_control
    - group.cooling_control
    - group.heat_control
    - group.misc_env

temperature:
  name: 'Temperature'
  entities:
    - sensor.average_indoor_temperature
    - sensor.average_indoor_temperature_rate
    - sensor.weather_temperature
    - sensor.outdoor_temperature_rate
    - sensor.indoor_outdoor_temperature_delta

cooling_control:
  name: 'Cooling Control'
  entities:
    - input_number.cooling_setpoint
    #- input_number.cooling_threshold
    - sensor.indoor_cooling_setpoint_temperature_delta
    - binary_sensor.average_cooling_required

fan_control:
  name: 'Living Room Fan Control'
  entities:
    - switch.living_room_fan
    - sensor.living_room_outdoor_temperature_delta
    - sensor.living_room_heating_setpoint_temperature_delta
    - sensor.living_room_cooling_setpoint_temperature_delta

heat_control:
  name: 'Heat Control'
  entities:
    - climate.bonus_room
    - switch.bonus_room_heater

misc_env:
  name: "Miscellaneous"
  entities:
    - sensor.average_humidity
    - sensor.average_light_level

environment_outside:
  name: 'Environment'
  entities:
    - weather.dark_sky
    - sun.sun
