esphomeyaml:
  name: bikeroom_multisensor
  platform: ESP8266
  board: nodemcuv2
  on_boot:
    then:
      - switch.turn_on: pir_power

wifi:
  ssid: !secret wifi1_name
  password: !secret wifi1_pw
  domain: !secret wifi_domain

mqtt:
  broker: !secret mqtt_server
  username: !secret mqtt1_un
  password: !secret mqtt1_pw

time:
  - platform: sntp
    id: sntp_time
    servers:
      - 192.168.1.1
      - 3.north-america.pool.ntp.org
      - 2.pool.ntp.org

# Enable logging
logger:

ota:
  password: !secret ota_pw

sensor:
  - platform: wifi_signal
    name: "Bike Room WiFi"
    update_interval: 15s
  - platform: dht
    model: DHT22
    pin: D7
    temperature:
      name: "Bike Room Temperature"
      id: "temperature"
    humidity:
      name: "Bike Room Humidity"
      id: "humidity"
  - platform: adc
    pin: A0
    name: "Bike Room Brightness"
    unit_of_measurement: lux
    filters:
      - lambda: >-
          return (x / 10000.0) * 2000000.0;
  - platform: template
    name: "Bike Room Absolute Humidity"
    lambda: >-
      return (6.112 * pow(2.7182818284, ((17.67 * id(temperature).value)/(id(temperature).value + 243.5))) * id(humidity).value * 2.1674)/(273.15 + id(temperature).value);
    update_interval: 15s
    accuracy_decimals: 2
    unit_of_measurement: "g/m³"
  - platform: uptime
    name: Bike Room Uptime

binary_sensor:
  - platform: gpio
    pin: D5
    name: "Bike Room Motion"
    device_class: motion
    filters:
      - delayed_on: 500ms
      - delayed_off: 1000ms
  - platform: gpio
    pin: D4
    name: "Bike Room Motion Up"
    device_class: motion
    filters:
      - delayed_on: 500ms
      - delayed_off: 1000ms
  - platform: status
    name: "Bike Room Status"

switch:
  - platform: gpio
    pin: D0
    id: pir_power
    name: "Bike Room Motion Up Power"
