esphomeyaml:
  name: bonusroom_multisensor
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi1_name
  password: !secret wifi1_pw
  domain: !secret wifi_domain

mqtt:
  broker: !secret mqtt_server
  username: !secret mqtt1_un
  password: !secret mqtt1_pw
  discovery: False

time:
  - platform: sntp
    id: sntp_time
    servers:
      - 3.north-america.pool.ntp.org
      - 2.pool.ntp.org

web_server:
  port: 80

# Enable logging
logger:

ota:
  password: !secret ota_pw

sensor:
  - platform: wifi_signal
    name: "Bonus Room WiFi"
    update_interval: 15s
  - platform: dht
    model: DHT22
    pin: D7
    temperature:
      name: "Bonus Room Temperature"
      id: "temperature"
    humidity:
      name: "Bonus Room Humidity"
      id: "humidity"
  - platform: adc
    pin: A0
    name: "Bonus Room Brightness"
    unit_of_measurement: lux
    filters:
      - lambda: >-
          return (x / 10000.0) * 2000000.0;
  - platform: template
    name: "Bonus Room Absolute Humidity"
    lambda: >-
      return (6.112 * pow(2.7182818284, ((17.67 * id(temperature).state)/(id(temperature).state + 243.5))) * id(humidity).state * 2.1674)/(273.15 + id(temperature).state);
    update_interval: 15s
    accuracy_decimals: 2
    unit_of_measurement: "g/m³"
  - platform: uptime
    name: Bonus Room Uptime

binary_sensor:
  - platform: gpio
    pin: D5
    name: "Bonus Room Motion"
    device_class: motion
    filters:
      - delayed_on: 500ms
      - delayed_off: 1000ms
  - platform: status
    name: "Bonus Room Status"

output:
  - platform: esp8266_pwm
    pin: D1
    id: redgpio
  - platform: esp8266_pwm
    pin: D2
    id: greengpio
  - platform: esp8266_pwm
    pin: D3
    id: bluegpio

light:
  - platform: rgb
    name: "Bonus Room LED"
    red: redgpio
    green: greengpio
    blue: bluegpio

switch:
  - platform: restart
    name: "Bonus Room Restart"
