esphome:
  name: masterbedroom_multisensor
  platform: ESP8266
  board: nodemcuv2

wifi:
  networks:
  - ssid: !secret wifi1_name
    password: !secret wifi1_pw
  - ssid: !secret wifi3_name
    password: !secret wifi3_pw
  - ssid: !secret wifi3_name
    password: !secret wifi3_pw
  domain: !secret wifi_domain

api:

time:
  - platform: sntp
    id: sntp_time
    servers:
      - 3.north-america.pool.ntp.org
      - 2.pool.ntp.org

web_server:
  port: 80

# Enable logging
logger:

ota:
  password: !secret ota_pw

sensor:
  - platform: wifi_signal
    name: "Master Bedroom WiFi"
    scan_interval: 15s
  - platform: dht
    model: DHT22
    pin: D7
    temperature:
      name: "Master Bedroom Temperature"
      id: "temperature"
    humidity:
      name: "Master Bedroom Humidity"
      id: "humidity"
  - platform: adc
    pin: A0
    name: "Master Bedroom Brightness"
    unit_of_measurement: lux
    filters:
      - lambda: >-
          return (x / 10000.0) * 2000000.0;
  - platform: template
    name: "Master Bedroom Absolute Humidity"
    lambda: >-
      return (6.112 * pow(2.7182818284, ((17.67 * id(temperature).state)/(id(temperature).state + 243.5))) * id(humidity).state * 2.1674)/(273.15 + id(temperature).state);
    scan_interval: 15s
    accuracy_decimals: 2
    unit_of_measurement: "g/m³"
  - platform: uptime
    name: Master Bedroom Uptime

binary_sensor:
  - platform: gpio
    pin: D5
    name: "Master Bedroom Motion"
    device_class: motion
    filters:
      - delayed_on: 500ms
      - delayed_off: 1000ms
  - platform: status
    name: "Master Bedroom Status"

output:
  - platform: esp8266_pwm
    pin: D1
    id: redgpio
  - platform: esp8266_pwm
    pin: D2
    id: greengpio
  - platform: esp8266_pwm
    pin: D3
    id: bluegpio

light:
  - platform: rgb
    name: "Master Bedroom LED"
    red: redgpio
    green: greengpio
    blue: bluegpio

switch:
  - platform: restart
    name: "Master Bedroom Restart"
