esphomeyaml:
  name: test_sensor
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi3_name
  password: !secret wifi3_pw
  domain: !secret wifi_domain

mqtt:
  broker: !secret mqtt_server
  username: !secret mqtt1_un
  password: !secret mqtt1_pw
  birth_message:
  will_message:

# Enable logging
logger:

web_server:
  port: 80

ota:
  password: !secret ota_pw

sensor:
  - platform: bme280
    temperature:
      name: "BME280 Temperature"
      oversampling: 16x
    pressure:
      name: "BME280 Pressure"
    humidity:
      name: "BME280 Humidity"
    address: 0x77
    update_interval: 15s

i2c:
  sda: D7
  scl: D8
  scan: False
