esphomeyaml:
  name: test_sensor
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi1_name
  password: !secret wifi1_pw
  domain: !secret wifi_domain

mqtt:
  broker: !secret mqtt_server
  username: !secret mqtt1_un
  password: !secret mqtt1_pw
  birth_message:
  will_message:

# Enable logging
logger:

#web_server:
#  port: 80

ota:
  password: !secret ota_pw

binary_sensor:
  - platform: gpio
    pin: D0
    name: "Test Motion"
    device_class: motion
