esphomeyaml:
  name: tv_bar_light
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi1_name
  password: !secret wifi1_pw
  domain: !secret wifi_domain

mqtt:
  broker: !secret mqtt_server
  username: !secret mqtt2_un
  password: !secret mqtt2_pw

# Enable logging
logger:

web_server:
  port: 80

ota:
  password: !secret ota_pw

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: D8
    num_leds: 7
    name: 'TV Bar Light'
    rgb_order: GRB
    effects:
      - strobe:
          name: Red Alert
          colors:
            - state: True
              brightness: 100%
              red: 100%
              green: 0%
              blue: 0%
              duration: 1s
            - state: False
              duration: 1s
      - fastled_color_wipe:
          name: Red Wipe
          colors:
              - red: 100%
                green: 0%
                blue: 0%
                num_leds: 2
              - red: 0%
                green: 0%
                blue: 0%
                num_leds: 2
      - fastled_color_wipe:
          name: Random Wipe
          colors:
              - random: True
                num_leds: 2
              - red: 0%
                green: 0%
                blue: 0%
                num_leds: 2
      - fastled_scan:
          name: Cylon
          move_interval: 100ms
      - fastled_flicker:
          name: Flicker
      - fastled_rainbow:
          name: Rainbow
          width: 40
      - fastled_rainbow:
          name: Fast Rainbow
          speed: 20
          width: 40
      - fastled_fireworks:
          name: Fireworks
          update_interval: 32ms
          spark_probability: 10%
          use_random_color: false
          fade_out_rate: 120
