esphomeyaml:
  name: tv_backlight
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi2_name
  password: !secret wifi2_pw
  domain: !secret wifi_domain

mqtt:
  broker: !secret mqtt_server
  username: !secret mqtt2_un
  password: !secret mqtt2_pw

# Enable logging
logger:

#web_server:
#  port: 80

ota:
  password: !secret ota_pw

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: D7
    num_leds: 91
    name: 'TV Backlight'
    rgb_order: GRB
    max_refresh_rate: 32ms
