esphomeyaml:
  name: tv_backlight
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi2_name
  password: !secret wifi2_pw
  domain: !secret wifi_domain

mqtt:
  broker: !secret mqtt_server
  username: !secret mqtt2_un
  password: !secret mqtt2_pw

# Enable logging
logger:

#web_server:
#  port: 80

ota:
  password: !secret ota_pw

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: D7
    num_leds: 91
    name: 'TV Backlight'
    color_correct: [100%,90%,95%]
    rgb_order: GRB
    effects:
      - strobe:
          name: Red Alert
          colors:
            - state: True
              brightness: 100%
              red: 100%
              green: 0%
              blue: 0%
              duration: 1s
            - state: False
              duration: 1s
      - fastled_color_wipe:
          name: Christmas Marquee
          add_led_interval: 120ms
          colors:
              - red: 100%
                green: 0%
                blue: 0%
                num_leds: 4
              - red: 0%
                green: 0%
                blue: 0%
                num_leds: 2
              - red: 0%
                green: 100%
                blue: 0%
                num_leds: 4
      - fastled_color_wipe:
          name: Random Wipe
          add_led_interval: 120ms
          colors:
              - random: True
                num_leds: 2
              - red: 0%
                green: 0%
                blue: 0%
                num_leds: 2
      - fastled_scan:
          name: Cylon
          move_interval: 120ms
      - fastled_flicker:
          name: Flicker
          intensity: 7%
      - fastled_rainbow:
          name: Rainbow
          width: 35
