esphomeyaml:
  name: tv_backlight
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi1_name
  password: !secret wifi1_pw
  domain: !secret wifi_domain

mqtt:
  broker: !secret mqtt_server
  username: !secret mqtt2_un
  password: !secret mqtt2_pw

# Enable logging
logger:

web_server:
  port: 80

ota:
  password: !secret ota_pw

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: GPIO3
    num_leds: 91
    name: 'TV Backlight'
    color_correct: [100%,85%,90%]
    rgb_order: GRB
    effects:
      - strobe:
          name: Red Alert
          colors:
            - state: True
              brightness: 100%
              red: 100%
              green: 0%
              blue: 0%
              duration: 1s
            - state: False
              duration: 1s
      - fastled_color_wipe:
          name: Christmas Marquee
          add_led_interval: 120ms
          colors:
              - red: 100%
                green: 0%
                blue: 0%
                num_leds: 18
              - red: 0%
                green: 0%
                blue: 0%
                num_leds: 10
              - red: 0%
                green: 100%
                blue: 0%
                num_leds: 18
      - fastled_color_wipe:
          name: Red Siren
          add_led_interval: 50ms
          colors:
              - red: 100%
                green: 0%
                blue: 0%
                num_leds: 26
              - red: 0%
                green: 0%
                blue: 0%
                num_leds: 19
      - fastled_color_wipe:
          name: Yellow Siren
          add_led_interval: 50ms
          colors:
              - red: 100%
                green: 90%
                blue: 0%
                num_leds: 26
              - red: 0%
                green: 0%
                blue: 0%
                num_leds: 19
      - fastled_color_wipe:
          name: Random Wipe
          add_led_interval: 120ms
          colors:
              - random: True
                num_leds: 20
              - red: 0%
                green: 0%
                blue: 0%
                num_leds: 10
      - fastled_rainbow:
          name: Rainbow
          width: 91
      - fastled_twinkle:
          name: Twinkle
          twinkle_probability: 5%
          progress_interval: 15ms
      - fastled_random_twinkle:
          name: Random Twinkle
          twinkle_probability: 5%
          progress_interval: 15ms
      - fastled_fireworks:
          name: Fireworks
          update_interval: 32ms
          spark_probability: 10%
          use_random_color: false
          fade_out_rate: 120
      - fastled_fireworks:
          name: Random Fireworks
          update_interval: 32ms
          spark_probability: 10%
          use_random_color: true
          fade_out_rate: 120
