esphomeyaml:
  name: tv_bar_light
  platform: ESP8266
  board: nodemcuv2

wifi:
  networks:
  - ssid: !secret wifi1_name
    password: !secret wifi1_pw
  - ssid: !secret wifi3_name
    password: !secret wifi3_pw
  - ssid: !secret wifi3_name
    password: !secret wifi3_pw
  domain: !secret wifi_domain

api:

# Enable logging
logger:

web_server:
  port: 80

ota:
  password: !secret ota_pw

light:
  - platform: neopixelbus
    chipset: WS2812X
    pin: D8
    num_leds: 7
    name: 'TV Bar Light'
    color_correct: [93%,100%,100%]
    rgb_order: GRB
    effects:
      - strobe:
          name: Red Alert
          colors:
            - state: True
              brightness: 100%
              red: 100%
              green: 0%
              blue: 0%
              duration: 1s
            - state: False
              duration: 1s
      - addressable_color_wipe:
          name: Red Wipe
          add_led_interval: 120ms
          colors:
              - red: 100%
                green: 0%
                blue: 0%
                num_leds: 2
              - red: 0%
                green: 0%
                blue: 0%
                num_leds: 2
      - addressable_color_wipe:
          name: Random Wipe
          add_led_interval: 120ms
          colors:
              - random: True
                num_leds: 2
              - red: 0%
                green: 0%
                blue: 0%
                num_leds: 2
      - addressable_scan:
          name: Cylon
          move_interval: 120ms
      - addressable_flicker:
          name: Flicker
          intensity: 7%
      - addressable_rainbow:
          name: Rainbow
          width: 35
      - addressable_rainbow:
          name: Fast Rainbow
          speed: 20
          width: 35
      - addressable_fireworks:
          name: Fireworks
          update_interval: 32ms
          spark_probability: 10%
          use_random_color: false
          fade_out_rate: 120
      - addressable_color_wipe:
          name: Christmas Wipe
          add_led_interval: 200ms
          colors:
              - red: 100%
                green: 0%
                blue: 0%
                num_leds: 2
              - red: 0%
                green: 0%
                blue: 0%
                num_leds: 1
              - red: 0%
                green: 100%
                blue: 0%
                num_leds: 2
              - red: 0%
                green: 0%
                blue: 0%
                num_leds: 1
