esphomeyaml:
  name: tv_bar_light
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi1_name
  password: !secret wifi1_pw
  domain: !secret wifi_domain

mqtt:
  broker: !secret mqtt_server
  username: !secret mqtt2_un
  password: !secret mqtt2_pw

# Enable logging
logger:

#web_server:
  port: 80

ota:
  password: !secret ota_pw

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: D8
    num_leds: 7
    name: 'TV Bar Light'
    rgb_order: GRB
    max_refresh_rate: 32ms
