- platform: usps
  scan_interval: 10

- platform: generic
  still_image_url: !secret city1_trafficcam1_url
  name: Traffic Camera

- platform: generic
  still_image:url: !secret city2_trafficcam1_url
  name: Trail Camera

- platform: onvif
  name: Garden Camera
  host: 192.168.1.81
  profile: 0
  username: !secret garden_camera1_un
  password: !secret garden_camera1_pw
