#- platform: usps
#  scan_interval: 10

- platform: generic
  still_image_url: !secret city1_trafficcam1_url
  name: Traffic Camera

- platform: generic
  still_image_url: !secret city2_trafficcam1_url
  name: Trail Camera

- platform: onvif
  name: Garden Camera 2
  host: 192.168.1.81
  profile: 0
  port: 1018

- platform: ffmpeg
  name: Garden Camera
  input: -rtsp_transport tcp -i rtsp://192.168.1.81:554/11 -an
