- platform: season
  type: astronomical

- platform: min_max
  friendly_name: "Average Temperature"
  name: "Average Indoor Temperature"
  entity_ids:
    - sensor.office_temperature
    - sensor.living_room_temperature
    - sensor.master_bedroom_temperature
    - sensor.bonus_room_temperature
    #- sensor.guest_bedroom_temperature
    #- sensor.sn6_temperature
  type: mean
  round_digits: 1

- platform: min_max
  name: "Average Humidity"
  entity_ids:
    - sensor.office_humidity
    - sensor.living_room_humidity
    - sensor.master_bedroom_humidity
    - sensor.bonus_room_humidity
    #- sensor.guest_bedroom_humidity
    #- sensor.sn6_humidity
  type: mean
  round_digits: 1

- platform: min_max
  name: "Average Light Level"
  entity_ids:
    - sensor.office_brightness
    - sensor.living_room_brightness
    - sensor.master_bedroom_brightness
    - sensor.bonus_room_brightness
    #- sensor.guest_bedroom_humidity
    - sensor.bike_room_brightness
  type: mean
  round_digits: 0

- platform: template
  sensors:
    indoor_outdoor_temperature_delta:
      friendly_name: "Outdoor Delta"
      value_template: '{{ ( ( states.sensor.average_indoor_temperature.state | float ) - ( states.weather.dark_sky.attributes.temperature | float ) ) | round(1) }}'
      unit_of_measurement: "Δ°F"

    indoor_cooling_setpoint_temperature_delta:
      friendly_name: "Cooling Setpoint Delta"
      value_template: '{{ ( ( states.sensor.average_indoor_temperature.state | float ) - ( states.input_number.cooling_setpoint.state | float ) ) | round(1) }}'
      unit_of_measurement: "Δ°F"

    living_room_outdoor_temperature_delta:
      friendly_name: "Living Room: Outdoor Delta"
      value_template: '{{ ( ( states.sensor.living_room_temperature.state | float ) - ( states.weather.dark_sky.attributes.temperature | float ) ) | round(1) }}'
      unit_of_measurement: "Δ°F"

    master_bedroom_outdoor_temperature_delta:
      friendly_name: "Master Bedroom: Outdoor Delta"
      value_template: '{{ ( ( states.sensor.master_bedroom_temperature.state | float ) - ( states.weather.dark_sky.attributes.temperature | float ) ) | round(1) }}'
      unit_of_measurement: "Δ°F"

    living_room_cooling_setpoint_temperature_delta:
      friendly_name: "Living Room: Cooling Setpoint Delta"
      value_template: '{{ ( ( states.sensor.living_room_temperature.state | float ) - ( states.input_number.cooling_setpoint.state | float ) ) | round(1) }}'
      unit_of_measurement: "Δ°F"
