- platform: template
  sensors:
    master_bedroom_temperature_rate:
      friendly_name: "Master Bedroom Temperature Change Rate"
      unit_of_measurement: "°F/H"
      value_template: "{{ ((states.binary_sensor.master_bedroom_temperature_trend.attributes.gradient | float) * 3600) | round(2) }}"
    living_room_temperature_rate:
      friendly_name: "Living Room Temperature Change Rate"
      unit_of_measurement: "°F/H"
      value_template: "{{ ((states.binary_sensor.living_room_temperature_trend.attributes.gradient | float) * 3600) | round(2) }}"
    office_temperature_rate:
      friendly_name: "Office Temperature Change Rate"
      unit_of_measurement: "°F/H"
      value_template: "{{ ((states.binary_sensor.office_temperature_trend.attributes.gradient | float) * 3600) | round(2) }}"
    bonus_room_temperature_rate:
      friendly_name: "Bonus Room Temperature Change Rate"
      unit_of_measurement: "°F/H"
      value_template: "{{ ((states.binary_sensor.bonus_room_temperature_trend.attributes.gradient | float) * 3600) | round(2) }}"
    bike_room_temperature_rate:
      friendly_name: "Bike Room Temperature Change Rate"
      unit_of_measurement: "°F/H"
      value_template: "{{ ((states.binary_sensor.bike_room_temperature_trend.attributes.gradient | float) * 3600) | round(2) }}"
    outdoor_temperature_rate:
      friendly_name: "Outdoor Temperature Change Rate"
      unit_of_measurement: "°F/H"
      value_template: "{{ ((states.binary_sensor.outdoor_temperature_trend.attributes.gradient | float) * 3600) | round(2) }}"

- platform: min_max
  name: "Average Indoor Temperature Rate"
  entity_ids:
    - sensor.bonus_room_temperature_rate
    - sensor.living_room_temperature_rate
    - sensor.master_bedroom_temperature_rate
    - sensor.office_temperature_rate
    - sensor.bike_room_temperature_rate
  type: mean
  round_digits: 2
