- platform: darksky
  name: Weather
  api_key: !secret darksky_api_key
  monitored_conditions:
    - summary
    - temperature
  update_interval: '00:30'
  
- platform: plex
  host: 192.168.1.20
  port: 32400
  name: Plex
  username: !secret plex_username
  password: !secret plex_password
  
- platform: speedtest
  name: Internet
  monitored_conditions:
    - ping
    - download
    - upload
  hour:
    - 0
    - 6
    - 12
    - 18
  minute: 0
  
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: since_last_boot
    - type: load_1m
    - type: network_in
      arg: eth0
    - type: network_out
      arg: eth0
      
- platform: cert_expiry
  host: !secret ha_url
  name: Home Assistant Certificate
  port: 8123
  
- platform: cert_expiry
  host: !secret iis_url
  name: IIS Certificate
  port: 443