- platform: mqtt
  state_topic: "bruh/livingroom"
  name: "SN2 Humidity"
  unit_of_measurement: "%"
  value_template: '{{ value_json.humidity | round(1) }}'

- platform: mqtt
  state_topic: "bruh/livingroom"
  name: "SN2 LDR"
  ##This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
  unit_of_measurement: "lx"
  value_template: '{{ value_json.ldr }}'

- platform: mqtt
  state_topic: "bruh/livingroom"
  name: "SN2 Temperature"
  unit_of_measurement: "째F"
  value_template: '{{ ( value_json.temperature | round(1) | float ) }}'



- platform: mqtt
  state_topic: "bruh/bonusroom"
  name: "SN4 Humidity"
  unit_of_measurement: "%"
  value_template: '{{ value_json.humidity | round(1) }}'

- platform: mqtt
  state_topic: "bruh/bonusroom"
  name: "SN4 LDR"
  ##This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
  unit_of_measurement: "lx"
  value_template: '{{ value_json.ldr }}'

- platform: mqtt
  state_topic: "bruh/bonusroom"
  name: "SN4 Temperature"
  unit_of_measurement: "째F"
  value_template: '{{ value_json.temperature | round(1) }}'



#- platform: mqtt
#  state_topic: "bruh/sensornode5"
#  name: "SN5 Humidity"
#  unit_of_measurement: "%"
#  value_template: '{{ value_json.humidity | round(1) }}'

#- platform: mqtt
#  state_topic: "bruh/sensornode5"
#  name: "SN5 LDR"
#  ##This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
#  unit_of_measurement: "lx"
#  value_template: '{{ value_json.ldr }}'

#- platform: mqtt
#  state_topic: "bruh/sensornode5"
#  name: "SN5 Temperature"
#  unit_of_measurement: "째F"
#  value_template: '{{ value_json.temperature | round(1) }}'



- platform: mqtt
  state_topic: "bruh/bikeroom"
  name: "Bike Room Humidity"
  unit_of_measurement: "%"
  value_template: '{{ value_json.humidity | round(1) }}'

- platform: mqtt
  state_topic: "bruh/bikeroom"
  name: "Bike Room Light Level"
  ##This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
  unit_of_measurement: "lx"
  value_template: '{{ value_json.ldr }}'

- platform: mqtt
  state_topic: "bruh/bikeroom"
  name: "Bike Room Temperature"
  unit_of_measurement: "째F"
  value_template: '{{ value_json.temperature | round(1) }}'
