- platform: snmp
  name: Router Uptime
  host: 192.168.1.1
  community: public
  baseoid: 1.3.6.1.2.1.1.3.0
  unit_of_measurement: 'minutes'
  value_template: '{{((value | int) / 6000) | int}}'

- platform: snmp
  name: Router RAM Usage
  host: 192.168.1.1
  community: public
  baseoid:  1.3.6.1.2.1.25.2.3.1.6.1
  value_template: '{{ ( ((value | float) / 255700 | int) * 100 ) | round(1) }}'
  unit_of_measurement: '%'

- platform: snmp
  name: Router CPU Usage
  host: 192.168.1.1
  community: public
  baseoid:  1.3.6.1.4.1.2021.10.1.3.1
  value_template: '{{ ((value | float) * 100) | int }}'
  unit_of_measurement: '%'

- platform: snmp
  name: Printer Status
  host: 192.168.1.133
  community: public
  baseoid: 1.3.6.1.2.1.25.3.2.1.5.1
  value_template: >
    {% if value == "1" %}
      Unknown
    {% elif value == "2" %}
      Normal
    {% elif value == "3" %}
      Warning
    {% elif value == "4" %}
      Testing
    {% elif value == "5" %}
      Error
    {% else %}
      {{ value }}
    {% endif %}

- platform: snmp
  name: Printer Uptime
  host: 192.168.1.133
  community: public
  baseoid: 1.3.6.1.2.1.1.3.0
  unit_of_measurement: 'minutes'
  value_template: '{{((value | int) / 6000) | int}}'
