#Batteries for other systems
#- platform: mqtt
#  state_topic: "battery/OVERLORD/Percentage"
#  name: "UPS Battery Percentage"
#  unit_of_measurement: "%"

#- platform: mqtt
#  state_topic: "battery/OVERLORD/RemainingMinutes"
#  name: "UPS Minutes Remaining"
#  unit_of_measurement: "min"

#- platform: mqtt
#  state_topic: "battery/OVERLORD/Status"
#  name: "UPS Status"

- platform: mqtt
  state_topic: "battery/OVERLORD/batteryState"
  name: "UPS Battery Status"

- platform: mqtt
  state_topic: "battery/OVERLORD/batteryRuntime"
  name: "UPS Runtime"
  unit_of_measurement: "min"
  force_update: true

- platform: mqtt
  state_topic: "battery/OVERLORD/batteryVoltage"
  name: "UPS Battery Voltage"
  unit_of_measurement: "V"

- platform: mqtt
  state_topic: "battery/OVERLORD/batteryCapacity"
  name: "UPS Battery Capacity"
  unit_of_measurement: "%"
  force_update: true

- platform: mqtt
  state_topic: "battery/OVERLORD/inputVoltage"
  name: "UPS Input Voltage"
  unit_of_measurement: "V"
  value_template: '{{ value | int }}'

- platform: mqtt
  state_topic: "battery/OVERLORD/outputVoltage"
  name: "UPS Output Voltage"
  unit_of_measurement: "V"
  value_template: '{{ value | int }}'

- platform: mqtt
  state_topic: "battery/OVERLORD/outputWatt"
  name: "UPS Output Wattage"
  unit_of_measurement: "W"

- platform: mqtt
  state_topic: "battery/OVERLORD/outputLoad"
  name: "UPS Output Load"
  unit_of_measurement: "%"

- platform: mqtt
  state_topic: "battery/OVERLORD/inputState"
  name: "UPS Input Status"

- platform: mqtt
  state_topic: "battery/OVERLORD/outputState"
  name: "UPS Output Status"

- platform: mqtt
  state_topic: "battery/OVERLORD/lastUpdate"
  name: "UPS Last Status Update"
  value_template: '{{ value | float | timestamp_local }}'

- platform: mqtt
  state_topic: "battery/OVERLORD/systemState"
  name: "UPS System Status"

- platform: template
  sensors:
    ups_full_capacity:
      friendly_name: "UPS Full Capacity"
      entity_id:
        - sensor.ups_current_capacity
        - sensor.ups_battery_capacity
        - sensor.ups_output_wattage
      value_template:  "{{ ((states('sensor.ups_current_capacity') | float) * (1 / (states('sensor.ups_battery_capacity') | float / 100))) | round(1) }}"
      unit_of_measurement: "Wh"
    ups_current_capacity:
      friendly_name: "UPS Current Capacity"
      entity_id:
        - sensor.ups_runtime
        - sensor.ups_output_wattage
      value_template:  "{{ ((states('sensor.ups_runtime') | float / 60) * (states('sensor.ups_output_wattage') | float)) | round(1) }}"
      unit_of_measurement: "Wh"
