- platform: season
  type: astronomical

- platform: darksky
  name: Outdoor
  api_key: !secret darksky_api_key
  monitored_conditions:
    - summary
    - temperature
    - humidity
    - wind_speed
    - wind_bearing
    - dew_point
    - apparent_temperature
    - precip_type
    - pressure
    - ozone
    - minutely_summary
    - hourly_summary
    - daily_summary
    - cloud_cover
    - visibility
    - precip_probability
    - temperature_low
    - temperature_high
    - apparent_temperature_low
    - apparent_temperature_high
    - precip_intensity_max
    - uv_index
  update_interval: '00:05'

- platform: min_max
  friendly_name: "Average Temperature"
  name: "Average Indoor Temperature"
  entity_ids:
    - sensor.office_temperature
    - sensor.living_room_temperature
    - sensor.master_bedroom_temperature
    - sensor.bonus_room_temperature
    #- sensor.guest_bedroom_temperature
    #- sensor.sn6_temperature
  type: mean
  round_digits: 1

- platform: min_max
  name: "Average Humidity"
  entity_ids:
    - sensor.office_humidity
    - sensor.living_room_humidity
    - sensor.master_bedroom_humidity
    - sensor.bonus_room_humidity
    #- sensor.guest_bedroom_humidity
    #- sensor.sn6_humidity
  type: mean
  round_digits: 1

- platform: min_max
  name: "Average Light Level"
  entity_ids:
    - sensor.office_brightness
    - sensor.living_room_brightness
    - sensor.master_bedroom_brightness
    - sensor.bonus_room_brightness
    #- sensor.guest_bedroom_humidity
    - sensor.bike_room_brightness
  type: mean
  round_digits: 0


- platform: statistics
  name: Office Temperature Stats
  entity_id: sensor.office_temperature
  max_age:
    minutes: 15
- platform: statistics
  name: Living Room Temperature Stats
  entity_id: sensor.living_room_temperature
  max_age:
    minutes: 15
- platform: statistics
  name: Master Bedroom Temperature Stats
  entity_id: sensor.master_bedroom_temperature
  max_age:
    minutes: 15
- platform: statistics
  name: Bonus Room Temperature Stats
  entity_id: sensor.bonus_room_temperature
  max_age:
    minutes: 15

- platform: filter
  name: "Living Room: Outdoor Temperature Delta"
  entity_id: sensor.living_room_outdoor_temperature_delta_raw
  filters:
    - filter: lowpass
      time_constant: 2
    - filter: time_simple_moving_average
      window_size: 00:15
      precision: 1

- platform: template
  sensors:
    living_room_fan_setpoint:
      friendly_name: "Living Room Fan Setpoint"
      value_template: '{{ (states.climate.living_room_fan.attributes.temperature | float) }}'
      unit_of_measurement: "°F"
    living_room_fan_setpoint_delta:
      friendly_name: "Living Room Fan Setpoint Delta"
      value_template: '{{ (states.climate.living_room_fan.attributes.current_temperature | float) - (states.climate.living_room_fan.attributes.temperature | float) }}'
      unit_of_measurement: "Δ°F"
    home_weather_temperature:
      friendly_name: "Home Weather Temperature"
      value_template: '{{ (states.weather.home_weather.attributes.temperature | float) }}'
      unit_of_measurement: "°F"

- platform: template
  sensors:
    indoor_outdoor_temperature_delta:
      friendly_name: "Outdoor Delta"
      value_template: '{{ ( ( states.sensor.average_indoor_temperature.state | float ) - ( states.sensor.outdoor_temperature.state | float ) ) | round(1) }}'
      unit_of_measurement: "Δ°F"

    living_room_outdoor_temperature_delta_raw:
      friendly_name: "Living Room: Outdoor Delta Raw"
      value_template: '{{ ( ( states.sensor.living_room_temperature.state | float ) - ( states.sensor.outdoor_temperature.state | float ) - (states.sensor.outdoor_temperature_rate.state | float / 2.0) ) }}'
      unit_of_measurement: "Δ°F"

    master_bedroom_outdoor_temperature_delta:
      friendly_name: "Master Bedroom: Outdoor Delta"
      value_template: '{{ ( ( states.sensor.master_bedroom_temperature.state | float ) - ( states.sensor.outdoor_temperature.state | float ) ) | round(1) }}'
      unit_of_measurement: "Δ°F"
