- platform: google_travel_time
  name: "Ryan to Chelsea Drive Time"
  api_key: !secret google_api_key
  origin: device_tracker.google_maps_110517150127386992510
  destination: device_tracker.google_maps_106557812104068122300
  scan_interval: 900

- platform: google_travel_time
  name: "Chelsea to Ryan Drive Time"
  api_key: !secret google_api_key
  origin: device_tracker.google_maps_106557812104068122300
  destination: device_tracker.google_maps_110517150127386992510
  scan_interval: 900

- platform: google_travel_time
  name: "Ryan to Home Drive Time"
  api_key: !secret google_api_key
  origin: device_tracker.google_maps_110517150127386992510
  destination: zone.home
  scan_interval: 900

- platform: google_travel_time
  name: "Chelsea to Home Drive Time"
  api_key: !secret google_api_key
  origin: device_tracker.google_maps_106557812104068122300
  destination: zone.home
  scan_interval: 900
