- platform: mqtt
  state_topic: "$SYS/broker/uptime"
  name: "MQTT Broker Uptime"

- platform: template
  sensors:
    day_of_year:
      friendly_name: 'Day of Year'
      unit_of_measurement: 'day'
      value_template: "{{ as_timestamp(now()) | timestamp_custom('%j', true) | int }}"

- platform: steam_online
  api_key: !secret steam_web_apikey
  accounts:
    - !secret steam_friend2
    - !secret steam_friend4
    - !secret steam_friend5
    - !secret steam_friend6
    - !secret steam_friend8

- platform: template
  sensors:
     solar_elevation:
       friendly_name: "Solar Elevation"
       unit_of_measurement: "°"
       value_template: >
        {% if states.sun.sun.attributes.elevation %}
          {{ states.sun.sun.attributes.elevation }}
        {% else %}
          0
        {% endif %}

- platform: template
  sensors:
    pioneer_volume_level:
      friendly_name: "Pioneer Volume Level"
      unit_of_measurement: "dB"
      value_template: >
        {% if states.media_player.pioneer_avr.attributes.volume_level %}
          {{ (((states.media_player.pioneer_avr.attributes.volume_level) | float) * 185 | round(0) / 2 ) - 80.5  }}
        {% else %}
          -80.5
        {% endif %}


- platform: dnsip
  ipv6: false
  scan_interval: 1200
- platform: dnsip
  hostname: !secret hostname
  ipv6: false
  scan_interval: 1200
