- platform: template
  sensors:
    master_bedroom_temperature_rate:
      friendly_name: "Master Bedroom Temperature Change Rate"
      unit_of_measurement: "°F/H"
      value_template: "{{ ((states.binary_sensor.master_bedroom_temperature_trend.attributes.gradient | float) * 3600) | round(2) }}"
    living_room_temperature_rate:
      friendly_name: "Living Room Temperature Change Rate"
      unit_of_measurement: "°F/H"
      value_template: "{{ ((states.binary_sensor.living_room_temperature_trend.attributes.gradient | float) * 3600) | round(2) }}"
    office_temperature_rate:
      friendly_name: "Office Temperature Change Rate"
      unit_of_measurement: "°F/H"
      value_template: "{{ ((states.binary_sensor.office_temperature_trend.attributes.gradient | float) * 3600) | round(2) }}"
    bonus_room_temperature_rate:
      friendly_name: "Bonus Room Temperature Change Rate"
      unit_of_measurement: "°F/H"
      value_template: "{{ ((states.binary_sensor.bonus_room_temperature_trend.attributes.gradient | float) * 3600) | round(2) }}"
    bike_room_temperature_rate:
      friendly_name: "Bike Room Temperature Change Rate"
      unit_of_measurement: "°F/H"
      value_template: "{{ ((states.binary_sensor.bike_room_temperature_trend.attributes.gradient | float) * 3600) | round(2) }}"
    outdoor_temperature_rate_raw:
      friendly_name: "Outdoor Temperature Change Rate Raw"
      unit_of_measurement: "°F/H"
      value_template: "{{ ((states.binary_sensor.outdoor_temperature_trend.attributes.gradient | float) * 3600) | round(2) }}"

- platform: filter
  name: "Outdoor Temperature Change Rate"
  entity_id: sensor.outdoor_temperature_rate_raw
  filters:
    - filter: outlier
      radius: 10.0 #This sensor updates every 5 minutes. I think this is conservative.
    - filter: lowpass
      time_constant: 4
    - filter: time_simple_moving_average
      window_size: 00:60
      precision: 1

- platform: min_max
  name: "Average Indoor Temperature Rate Raw"
  entity_ids:
    - sensor.bonus_room_temperature_rate
    - sensor.living_room_temperature_rate
    - sensor.master_bedroom_temperature_rate
    - sensor.office_temperature_rate
    - sensor.bike_room_temperature_rate
  type: mean
  round_digits: 2

- platform: filter
  name: "Average Indoor Temperature Rate"
  entity_id: sensor.average_indoor_temperature_rate_raw
  filters:
    - filter: lowpass
      time_constant: 4
    - filter: time_simple_moving_average
      window_size: 00:30
      precision: 1
