#Chromecast
- platform: cast
  host: 192.168.1.101

- platform: plex

- platform: pioneer
  host: 192.168.1.104

- platform: universal
  name: 'Living Room Media Center'
  children:
    - media_player.living_room_chromecast
    - media_player.pioneer_avr
    - media_player.master
  commands:
    turn_on:
      service: remote.turn_on
      data:
        entity_id: remote.living_room
        activity: 'Watch Chromecast'
    turn_off:
      service: remote.turn_off
      data:
        entity_id: remote.living_room
    volume_up:
      service: media_player.volume_up
      data:
        entity_id: media_player.pioneer_avr
    volume_down:
      service: media_player.volume_down
      data:
        entity_id: media_player.pioneer_avr
    volume_mute:
      service: media_player.volume_mute
      data:
        entity_id: media_player.pioneer_avr
    volume_set:
      service: media_player.volume_set
      data_template:
        entity_id: media_player.pioneer_avr
        volume_level: '{{ volume_level }}'
    select_source:
      service: remote.turn_on
      data_template:
        entity_id: remote.living_room
        activity: '{{ source }}'
    attributes:
      state: remote.living_room
      is_volume_muted: media_player.pioneer_avr|is_volume_muted
      volume_level: media_player.pioneer_avr|volume_level
      source: remote.living_room|current_activity
      source_list: input_select.harmony_activity_select|options
