esphome:
  name: garden_probe
  platform: ESP32
  board: nodemcu-32s

wifi:
  networks:
  - ssid: !secret wifi1_name
    password: !secret wifi1_pw
  - ssid: !secret wifi3_name
    password: !secret wifi3_pw
  - ssid: !secret wifi3_name
    password: !secret wifi3_pw
  domain: !secret wifi_domain

api:

# Enable logging
logger:

web_server:
  port: 80

ota:
  password: !secret ota_pw

esp32_ble_tracker:

sensor:
  - platform: xiaomi_miflora
    mac_address: !secret miflora_mac
    temperature:
      name: "Garden Temperature"
    moisture:
      name: "Garden Soil Moisture"
    illuminance:
      name: "Garden Illuminance"
    conductivity:
      name: "Garden Soil Conductivity"
    battery_level:
      name: "Garden Sensor Battery Level"
