esphome:
  name: livingroom_multisensor
  platform: ESP8266
  board: nodemcuv2

wifi:
  networks:
  - ssid: !secret wifi1_name
    password: !secret wifi1_pw
  domain: !secret wifi_domain

api:

time:
  - platform: sntp
    id: sntp_time
    servers:
      - 3.north-america.pool.ntp.org
      - 2.pool.ntp.org

web_server:
  port: 80

# Enable logging
logger:

ota:
  password: !secret ota_pw

sensor:
  - platform: dht
    model: DHT22
    pin: D7
    temperature:
      name: "Living Room Temperature"
      id: "temperature"
      accuracy_decimals: 1
      unit_of_measurement: "°F"
      filters:
        - sliding_window_moving_average:
            window_size: 5
            send_every: 5
        - lambda: return x * (9.0/5.0) + 32.0;
    humidity:
      name: "Living Room Humidity"
      id: "humidity"
      accuracy_decimals: 1
      filters:
      - sliding_window_moving_average:
          window_size: 5
          send_every: 5
  - platform: adc
    pin: A0
    name: "Living Room Brightness"
    unit_of_measurement: lux
    filters:
      - lambda: >-
          return (x / 10000.0) * 2000000.0;
  - platform: template
    name: "Living Room Absolute Humidity"
    lambda: >-
      return (6.112 * pow(2.7182818284, ((17.67 * id(temperature).state)/(id(temperature).state + 243.5))) * id(humidity).state * 2.1674)/(273.15 + id(temperature).state);
    update_interval: 15s
    accuracy_decimals: 2
    unit_of_measurement: "g/m³"

binary_sensor:
  - platform: gpio
    pin: D5
    name: "Living Room Motion"
    device_class: motion
    filters:
      - delayed_on: 500ms
      - delayed_off: 1000ms
  - platform: status
    name: "Living Room Status"

output:
  - platform: esp8266_pwm
    pin: D1
    id: redgpio
  - platform: esp8266_pwm
    pin: D2
    id: greengpio
  - platform: esp8266_pwm
    pin: D3
    id: bluegpio

light:
  - platform: rgb
    name: "Living Room LED"
    red: redgpio
    green: greengpio
    blue: bluegpio

switch:
  - platform: restart
    name: "Living Room Restart"
