esphome:
  name: masterbedroom_lamps
  platform: ESP8266
  board: esp01_1m

wifi:
  networks:
  - ssid: !secret wifi1_name
    password: !secret wifi1_pw
  - ssid: !secret wifi3_name
    password: !secret wifi3_pw
  - ssid: !secret wifi3_name
    password: !secret wifi3_pw
  domain: !secret wifi_domain

api:

# Enable logging
logger:

web_server:
  port: 80

ota:
  password: !secret ota_pw

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO10
      mode: INPUT_PULLUP
      inverted: True
    on_click:
      then:
        - light.toggle: ryan_lamp
    on_double_click:
      then:
        - light.toggle: chelsea_lamp
    name: "Master Bedroom Switch Button"
  - platform: status
    name: "Master Bedroom Switch Status"

output:
  - platform: gpio
    id: ryan_lamp_output
    pin: GPIO12
  - platform: gpio
    id: chelsea_lamp_output
    pin: GPIO5

light:
  - platform: binary
    name: "Ryan Nightstand Lamp"
    id: ryan_lamp
    output: ryan_lamp_output
  - platform: binary
    name: "Chelsea Nightstand Lamp"
    id: chelsea_lamp
    output: chelsea_lamp_output
