esphome:
  name: office_multisensor
  platform: ESP8266
  board: nodemcuv2

wifi:
  networks:
  - ssid: !secret wifi1_name
    password: !secret wifi1_pw
  domain: !secret wifi_domain

api:

time:
  - platform: sntp
    id: sntp_time
    servers:
      - 3.north-america.pool.ntp.org
      - 2.pool.ntp.org

web_server:
  port: 80

# Enable logging
logger:

ota:
  password: !secret ota_pw
  
i2c:
  sda: D2
  scl: D1

sensor:
  - platform: dht
    model: DHT22
    pin: D7
    temperature:
      name: "Office Temperature"
      id: "temperature"
      filters:
        - sliding_window_moving_average:
            window_size: 5
            send_every: 5
    humidity:
      name: "Office Humidity"
      id: "humidity"
      accuracy_decimals: 1
      filters:
      - sliding_window_moving_average:
          window_size: 5
          send_every: 5
  - platform: adc
    pin: A0
    name: "Office Brightness"
    unit_of_measurement: lux
    filters:
      - lambda: >-
          return x * 200.0;
      - exponential_moving_average:
          alpha: 0.2
          send_every: 3
  - platform: ccs811
    eco2:
      name: "Office CO2"
      filters:
      - filter_out: 65021
      - filter_out: 0
    tvoc:
      name: "Office VOC"
      filters:
      - filter_out: 65021
      - filter_out: 0
    update_interval: 60s
    address: 0x5A
    humidity: humidity
    temperature: temperature
    
binary_sensor:
  - platform: gpio
    pin: D5
    name: "Office Motion"
    device_class: motion
    filters:
      - delayed_on: 500ms
      - delayed_off: 1000ms
  - platform: status
    name: "Office Status"

switch:
  - platform: restart
    name: "Office Restart"
