esphome:
  name: test_co
  platform: ESP8266
  board: nodemcuv2

wifi:
  networks:
  - ssid: !secret wifi1_name
    password: !secret wifi1_pw
  domain: !secret wifi_domain

api:

# Enable logging
logger:

web_server:
  port: 80

ota:
  password: !secret ota_pw

i2c:
  sda: D2
  scl: D1

sensor:
  - platform: ccs811
    eco2:
      name: "CCS811 B CO₂"
      filters:
      - filter_out: 65021
      - filter_out: 0
    tvoc:
      name: "CCS811 B Total Volatile Organic Compound"
      filters:
      - filter_out: 65021
      - filter_out: 0
    update_interval: 60s
    address: 0x5A
  - platform: ccs811
    eco2:
      name: "CCS811 J CO₂"
      filters:
      - filter_out: 65021
      - filter_out: 0
    tvoc:
      name: "CCS811 J Total Volatile Organic Compound"
      filters:
      - filter_out: 65021
      - filter_out: 0
    update_interval: 60s
    address: 0x5B