esphome:
  name: test_sensor
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi3_name
  password: !secret wifi3_pw
  domain: !secret wifi_domain

mqtt:
  broker: !secret mqtt_server
  username: !secret mqtt1_un
  password: !secret mqtt1_pw

# Enable logging
logger:

web_server:
  port: 80

ota:
  password: !secret ota_pw

sensor:
  - platform: bme280
    temperature:
      name: "BME280 Temperature"
      id: "temperature"
    pressure:
      name: "BME280 Pressure"
      id: "pressure"
    humidity:
      name: "BME280 Humidity"
      id: "humidity"
    address: 0x76
    iir_filter: 2x
  - platform: template
    name: "BME280 Absolute Humidity"
    lambda: >-
      return (6.112 * pow(2.7182818284, ((17.67 * id(temperature).value)/(id(temperature).value + 243.5))) * id(humidity).value * 2.1674)/(273.15 + id(temperature).value);
    scan_interval: 15s
    accuracy_decimals: 2
    unit_of_measurement: "g/m³"

i2c:
  sda: D2
  scl: D1
  scan: False
