esphome:
  name: tv_backlight
  platform: ESP8266
  board: nodemcuv2

wifi:
  networks:
  - ssid: !secret wifi1_name
    password: !secret wifi1_pw
  domain: !secret wifi_domain

api:

# Enable logging
logger:

web_server:
  port: 80

ota:
  password: !secret ota_pw

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: GPIO3
    num_leds: 91
    name: 'TV Backlight'
    color_correct: [100%,90%,90%]
    rgb_order: GRB
    effects:
      - strobe:
          name: Red Alert
          colors:
            - state: True
              brightness: 100%
              red: 100%
              green: 0%
              blue: 0%
              duration: 1s
            - state: False
              duration: 1s
      - addressable_color_wipe:
          name: Christmas Marquee
          add_led_interval: 120ms
          colors:
              - red: 100%
                green: 0%
                blue: 0%
                num_leds: 22
              - red: 0%
                green: 0%
                blue: 0%
                num_leds: 5
              - red: 0%
                green: 100%
                blue: 0%
                num_leds: 14
              - red: 0%
                green: 0%
                blue: 0%
                num_leds: 5
      - addressable_color_wipe:
          name: Red Siren
          add_led_interval: 50ms
          colors:
              - red: 100%
                green: 0%
                blue: 0%
                num_leds: 26
              - red: 0%
                green: 0%
                blue: 0%
                num_leds: 19
      - addressable_color_wipe:
          name: Yellow Siren
          add_led_interval: 50ms
          colors:
              - red: 100%
                green: 90%
                blue: 0%
                num_leds: 26
              - red: 0%
                green: 0%
                blue: 0%
                num_leds: 19
      - addressable_color_wipe:
          name: Random Wipe
          add_led_interval: 120ms
          colors:
              - random: True
                num_leds: 20
              - red: 0%
                green: 0%
                blue: 0%
                num_leds: 10
      - addressable_rainbow:
          name: Rainbow
          width: 91
      - addressable_twinkle:
          name: Twinkle
          twinkle_probability: 5%
          progress_interval: 15ms
      - addressable_random_twinkle:
          name: Random Twinkle
          twinkle_probability: 5%
          progress_interval: 15ms
      - addressable_fireworks:
          name: Fireworks
          update_interval: 32ms
          spark_probability: 10%
          use_random_color: false
          fade_out_rate: 120
      - addressable_fireworks:
          name: Random Fireworks
          update_interval: 32ms
          spark_probability: 10%
          use_random_color: true
          fade_out_rate: 120
      - addressable_flicker:
          name: Shields Up
          update_interval: 32ms
          intensity: 10%
