esphome:
  name: xmas_wreath
  platform: ESP8266
  board: esp01_1m

wifi:
  networks:
  - ssid: !secret wifi1_name
    password: !secret wifi1_pw
  domain: !secret wifi_domain

api:

# Enable logging
logger:

web_server:
  port: 80

ota:
  password: !secret ota_pw

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      then:
        - light.toggle: relay_light
    name: "Christmas Wreath Switch Button"
  - platform: status
    name: "Christmas Lamp Switch Status"

output:
  - platform: gpio
    id: relay_output
    pin: GPIO12

light:
  - platform: binary
    name: "Christmas Wreath"
    output: relay_output
    id: relay_light

status_led:
  pin:
    number: GPIO13
    inverted: True
