sensor:
  - platform: mqtt
    name: Bike Room Temperature
    state_topic: bikeroom_multisensor/sensor/bike_room_temperature/state
    availability_topic: bikeroom_multisensor/status
    unit_of_measurement: '°C'
    device_class: temperature
  - platform: mqtt
    name: Bike Room Humidity
    state_topic: bikeroom_multisensor/sensor/bike_room_humidity/state
    availability_topic: bikeroom_multisensor/status
    unit_of_measurement: '%'
    device_class: humidity
  - platform: mqtt
    name: Bike Room Brightness
    state_topic: bikeroom_multisensor/sensor/bike_room_brightness/state
    availability_topic: bikeroom_multisensor/status
    unit_of_measurement: lux
  - platform: mqtt
    name: Bike Room Absolute Humidity
    state_topic: bikeroom_multisensor/sensor/bike_room_absolute_humidity/state
    availability_topic: bikeroom_multisensor/status
    unit_of_measurement: g/m³

  - platform: mqtt
    name: Bonus Room Temperature
    state_topic: bonusroom_multisensor/sensor/bonus_room_temperature/state
    availability_topic: bonusroom_multisensor/status
    unit_of_measurement: '°C'
    device_class: temperature
  - platform: mqtt
    name: Bonus Room Humidity
    state_topic: bonusroom_multisensor/sensor/bonus_room_humidity/state
    availability_topic: bonusroom_multisensor/status
    unit_of_measurement: '%'
    device_class: humidity
  - platform: mqtt
    name: Bonus Room Brightness
    state_topic: bonusroom_multisensor/sensor/bonus_room_brightness/state
    availability_topic: bonusroom_multisensor/status
    unit_of_measurement: lux
  - platform: mqtt
    name: Bonus Room Absolute Humidity
    state_topic: bonusroom_multisensor/sensor/bonus_room_absolute_humidity/state
    availability_topic: bonusroom_multisensor/status
    unit_of_measurement: g/m³

  - platform: mqtt
    name: Living Room Temperature
    state_topic: livingroom_multisensor/sensor/living_room_temperature/state
    availability_topic: livingroom_multisensor/status
    unit_of_measurement: '°C'
    device_class: temperature
  - platform: mqtt
    name: Living Room Humidity
    state_topic: livingroom_multisensor/sensor/living_room_humidity/state
    availability_topic: livingroom_multisensor/status
    unit_of_measurement: '%'
    device_class: humidity
  - platform: mqtt
    name: Living Room Brightness
    state_topic: livingroom_multisensor/sensor/living_room_brightness/state
    availability_topic: livingroom_multisensor/status
    unit_of_measurement: lux
  - platform: mqtt
    name: Living Room Absolute Humidity
    state_topic: livingroom_multisensor/sensor/living_room_absolute_humidity/state
    availability_topic: livingroom_multisensor/status
    unit_of_measurement: g/m³

  - platform: mqtt
    name: Master Bedroom Temperature
    state_topic: masterbedroom_multisensor/sensor/master_bedroom_temperature/state
    availability_topic: masterbedroom_multisensor/status
    unit_of_measurement: '°C'
    device_class: temperature
  - platform: mqtt
    name: Master Bedroom Humidity
    state_topic: masterbedroom_multisensor/sensor/master_bedroom_humidity/state
    availability_topic: masterbedroom_multisensor/status
    unit_of_measurement: '%'
    device_class: humidity
  - platform: mqtt
    name: Master Bedroom Brightness
    state_topic: masterbedroom_multisensor/sensor/master_bedroom_brightness/state
    availability_topic: masterbedroom_multisensor/status
    unit_of_measurement: lux
  - platform: mqtt
    name: Master Bedroom Absolute Humidity
    state_topic: masterbedroom_multisensor/sensor/master_bedroom_absolute_humidity/state
    availability_topic: masterbedroom_multisensor/status
    unit_of_measurement: g/m³

  - platform: mqtt
    name: Office Temperature
    state_topic: office_multisensor/sensor/office_temperature/state
    availability_topic: office_multisensor/status
    unit_of_measurement: '°C'
    device_class: temperature
  - platform: mqtt
    name: Office Humidity
    state_topic: office_multisensor/sensor/office_humidity/state
    availability_topic: office_multisensor/status
    unit_of_measurement: '%'
    device_class: humidity
  - platform: mqtt
    name: Office Brightness
    state_topic: office_multisensor/sensor/office_brightness/state
    availability_topic: office_multisensor/status
    unit_of_measurement: lux
  - platform: mqtt
    name: Office Absolute Humidity
    state_topic: office_multisensor/sensor/office_absolute_humidity/state
    availability_topic: office_multisensor/status
    unit_of_measurement: g/m³

binary_sensor:
  - platform: mqtt
    name: Bike Room Motion
    state_topic: bikeroom_multisensor/binary_sensor/bike_room_motion/state
    availability_topic: bikeroom_multisensor/status
    device_class: motion
  - platform: mqtt
    name: Bike Room Status
    state_topic: bikeroom_multisensor/binary_sensor/bike_room_status/state
    availability_topic: bikeroom_multisensor/status

  - platform: mqtt
    name: Living Room Motion
    state_topic: livingroom_multisensor/binary_sensor/living_room_motion/state
    availability_topic: livingroom_multisensor/status
    device_class: motion
  - platform: mqtt
    name: Living Room Status
    state_topic: livingroom_multisensor/binary_sensor/living_room_status/state
    availability_topic: livingroom_multisensor/status

  - platform: mqtt
    name: Bonus Room Motion
    state_topic: bonusroom_multisensor/binary_sensor/bonus_room_motion/state
    availability_topic: bonusroom_multisensor/status
    device_class: motion
  - platform: mqtt
    name: Bonus Room Status
    state_topic: bonusroom_multisensor/binary_sensor/bonus_room_status/state
    availability_topic: bonusroom_multisensor/status

  - platform: mqtt
    name: Master Bedroom Motion
    state_topic: masterbedroom_multisensor/binary_sensor/master_bedroom_motion/state
    availability_topic: masterbedroom_multisensor/status
    device_class: motion
  - platform: mqtt
    name: Master Bedroom Status
    state_topic: masterbedroom_multisensor/binary_sensor/master_bedroom_status/state
    availability_topic: masterbedroom_multisensor/status

  - platform: mqtt
    name: Office Motion
    state_topic: office_multisensor/binary_sensor/office_motion/state
    availability_topic: office_multisensor/status
    device_class: motion
  - platform: mqtt
    name: Office Status
    state_topic: office_multisensor/binary_sensor/office_status/state
    availability_topic: office_multisensor/status

light:
  - platform: mqtt
    schema: json
    name: Bonus Room LED
    state_topic: bonusroom_multisensor/light/bonus_room_led/state
    command_topic: bonusroom_multisensor/light/bonus_room_led/command
    availability_topic: bonusroom_multisensor/status
    brightness: true
    rgb: true

  - platform: mqtt
    schema: json
    name: Living Room LED
    state_topic: livingroom_multisensor/light/living_room_led/state
    command_topic: livingroom_multisensor/light/living_room_led/command
    availability_topic: livingroom_multisensor/status
    brightness: true
    rgb: true

  - platform: mqtt
    schema: json
    name: Master Bedroom LED
    state_topic: masterbedroom_multisensor/light/master_bedroom_led/state
    command_topic: masterbedroom_multisensor/light/master_bedroom_led/command
    availability_topic: masterbedroom_multisensor/status
    brightness: true
    rgb: true

  - platform: mqtt
    schema: json
    name: Office LED
    state_topic: office_multisensor/light/office_led/state
    command_topic: office_multisensor/light/office_led/command
    availability_topic: office_multisensor/status
    brightness: true
    rgb: true

switch:
  - platform: mqtt
    name: Bike Room Motion Up Power
    state_topic: bikeroom_multisensor/switch/bike_room_motion_up_power/state
    command_topic: bikeroom_multisensor/switch/bike_room_motion_up_power/command
    availability_topic: bikeroom_multisensor/status
  - platform: mqtt
    name: Bike Room Restart
    state_topic: bikeroom_multisensor/switch/bike_room_restart/state
    command_topic: bikeroom_multisensor/switch/bike_room_restart/command
    availability_topic: bikeroom_multisensor/status
  - platform: mqtt
    name: Bonus Room Restart
    state_topic: bonusroom_multisensor/switch/bonus_room_restart/state
    command_topic: bonusroom_multisensor/switch/bonus_room_restart/command
    availability_topic: bonusroom_multisensor/status
  - platform: mqtt
    name: Living Room Restart
    state_topic: livingroom_multisensor/switch/living_room_restart/state
    command_topic: livingroom_multisensor/switch/living_room_restart/command
    availability_topic: livingroom_multisensor/status
  - platform: mqtt
    name: Master Bedroom Restart
    state_topic: masterbedroom_multisensor/switch/master_bedroom_restart/state
    command_topic: masterbedroom_multisensor/switch/master_bedroom_restart/command
    availability_topic: masterbedroom_multisensor/status
  - platform: mqtt
    name: Office Restart
    state_topic: office_multisensor/switch/office_restart/state
    command_topic: office_multisensor/switch/office_restart/command
    availability_topic: office_multisensor/status
