weather:
  - platform: openweathermap
    api_key: !secret openweathermap_api_key
    name: "Home Weather"
    mode: hourly

iqvia:
    zip_code: !secret home_zip
    monitored_conditions:
      - allergy_average_forecasted
      - allergy_index_today
      - allergy_index_tomorrow
      - disease_average_forecasted

sensor:
  - platform: template
    sensors:
      home_weather_temperature:
        friendly_name: "Home Weather Temperature"
        value_template: '{{ (states.weather.home_weather.attributes.temperature | float) }}'
        unit_of_measurement: "°F"
