binary_sensor:
  - platform: template
    sensors:
      everybody_home:
        friendly_name: 'Everybody Home'
        device_class: presence
        value_template: >
          {% if is_state('person.ryan', 'home')
             and is_state('person.chelsea', 'home') %}
           True
           {% else %}
           False
           {% endif %}
      everybody_home_or_distant:
        friendly_name: 'Everybody Home or Distant'
        device_class: presence
        value_template: >
          {% if is_state('binary_sensor.everybody_home', 'on') %}
          True
          {% elif is_state('person.ryan', 'home')
            and (states('sensor.chelsea_distance_from_home') | float > 3) %}
          True
          {% elif is_state('person.chelsea', 'home')
            and (states('sensor.ryan_distance_from_home') | float > 3) %}
          True
          {% elif (states('sensor.chelsea_distance_from_home') | float > 3)
            and (states('sensor.ryan_distance_from_home') | float > 3)  %}
          True
          {% else %}
          False
          {% endif %}
      anybody_home:
        #The new Persons feature is awesome - but there's no built-in way to
        #ask "is ANY person home?" As an alternative, here's some template
        #sorcery to do the same thing.
        friendly_name: 'Anybody Home'
        device_class: presence
        entity_id:
          - sensor.solar_elevation
        value_template: >
          {% set ns = namespace(found=false) %}
          {% for state in states.person %}
            {% if state.state == 'home' %}
              {% set ns.found = true %}
            {% endif %}
          {% endfor %}
          {{ns.found}}
