binary_sensor:
  - platform: template
    sensors:
      summer_hotter_inside:
        friendly_name: "Hotter Inside than Outside"
        device_class: heat
        delay_on:
          minutes: 1
        delay_off:
          minutes: 1
        value_template: >-
          {{ states('sensor.outdoor_temperature_sensor')|float < states('sensor.living_room_temperature')|float }}
      summer_hotter_inside_than_target:
        friendly_name: "Hotter Inside than Target"
        device_class: heat
        delay_on:
          minutes: 1
        delay_off:
          minutes: 1
        value_template: >-
          {{ states('sensor.living_room_temperature')|float > states('input_number.summer_desired_temperature')|float }}
      summer_hotter_outside_than_limit:
        friendly_name: "Hotter Outside than Limit"
        device_class: heat
        delay_on:
          minutes: 1
        delay_off:
          minutes: 1
        value_template: >-
          {{ states('sensor.outdoor_temperature_sensor')|float > states('input_number.summer_max_outdoor_window_open_temperature') }}
      summer_open_window:
        friendly_name: "OK to Open Windows"
        device_class: window
        delay_on:
          minutes: 5
        delay_off: 
          minutes: 5
        value_template: >
          {{ is_state('binary_sensor.summer_hotter_inside', 'on') and is_state('binary_sensor.summer_hotter_inside_than_target', 'on') and is_state('binary_sensor.summer_hotter_outside_than_limit', 'off') }}

input_number:
  summer_desired_temperature:
    name: Desired Temperature
    initial: 70
    min: 60
    max: 80
    step: 1
    unit_of_measurement: '°F'
    icon: mdi:thermometer
  summer_max_outdoor_window_open_temperature:
    name: Max Outdoor Temperature
    initial: 77
    min: 75
    max: 85
    step: 1
    unit_of_measurement: '°F'
    icon: mdi:thermometer-alert