automation:
  - id: lights_left_on
    alias: 'Notification Light: Lights Left On'
    trigger:
      - platform: time_pattern
        minutes: '/3'
        seconds: 40
      - platform: state
        entity_id: group.indoor_lights
        to: 'on'
      - platform: state
        entity_id: remote.living_room
        to: 'on'
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: group.indoor_lights
          state: 'on'
        - condition: state
          entity_id: remote.living_room
          state: 'on'
    action:
      - service: light.turn_on
        data:
          entity_id: light.master_bedroom_led
          color_name: white
          brightness: 32
          transition: 10

  - id: lights_turned_off
    alias: 'Notification Light: Lights Turned Off'
    trigger:
      - platform: time_pattern
        minutes: '/3'
        seconds: 50
      - platform: state
        entity_id: group.indoor_lights
        to: 'off'
      - platform: state
        entity_id: remote.living_room
        to: 'off'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: group.indoor_lights
          state: 'off'
        - condition: state
          entity_id: remote.living_room
          state: 'off'
    action:
      - service: light.turn_off
        data:
          entity_id: light.master_bedroom_led
          transition: 10
