binary_sensor:
  - platform: ping
    host: 192.168.1.33
    name: Living Room TV Ping

  - platform: ping
    host: 192.168.1.30
    name: Living Room Harmony Ping

  - platform: ping
    host: 192.168.1.20
    name: Domain Controller Ping

  - platform: ping
    host: 192.168.1.25
    name: Media Center PC Ping

  - platform: ping
    host: 192.168.1.1
    name: Gateway Ping

  - platform: ping
    host: 192.168.1.133
    name: Printer Ping

  - platform: ping
    host: 192.168.1.34
    name: Lutron Smart Bridge Ping

  - platform: ping
    host: 192.168.100.1
    name: Modem Ping

  - platform: ping
    host: 192.168.1.2
    name: Switch Ping

sensor:
  - platform: template
    sensors:
      ryan_phone_battery:
        friendly_name: "Ryan Phone Battery"
        value_template: >
          {% if states.device_tracker.ryan_phone %}
            {{ states.device_tracker.ryan_phone.attributes.battery | int }}
          {% else %}
            unknown
          {% endif %}
        unit_of_measurement: '%'
        icon_template: >
          {% if states.device_tracker.ryan_phone.attributes.battery >= 90 %}
            mdi:battery
          {% elif states.device_tracker.ryan_phone.attributes.battery > 0 %}
            mdi:battery-{{(states.device_tracker.ryan_phone.attributes.battery | int / 10) | int + 1}}0
          {% else %}
            mdi:battery-unknown
          {% endif %}

  - platform: template
    sensors:
      chelsea_phone_battery:
        friendly_name: "Chelsea Phone Battery"
        value_template: >
          {% if states.device_tracker.chelsea_phone %}
            {{ states.device_tracker.chelsea_phone.attributes.battery | int }}
          {% else %}
            unknown
          {% endif %}
        unit_of_measurement: '%'
        icon_template: >
          {% if states.device_tracker.chelsea_phone.attributes.battery >= 90 %}
            mdi:battery
          {% elif states.device_tracker.chelsea_phone.attributes.battery > 0 %}
            mdi:battery-{{(states.device_tracker.chelsea_phone.attributes.battery | int / 10) | int + 1}}0
          {% else %}
            mdi:battery-unknown
          {% endif %}
  - platform: steam_online
    api_key: !secret steam_web_apikey
    accounts:
      - !secret steam_friend2
      - !secret steam_friend4
      - !secret steam_friend5
      - !secret steam_friend6
      - !secret steam_friend8
