sensor:
  - platform: min_max
    name: "Average Humidity"
    entity_ids:
      - sensor.office_humidity
      - sensor.living_room_humidity
      - sensor.master_bedroom_humidity
      - sensor.bonus_room_humidity
    type: mean
    round_digits: 1

  - platform: min_max
    name: "Average Light Level"
    entity_ids:
      - sensor.office_brightness
      - sensor.living_room_brightness
      - sensor.master_bedroom_brightness
      - sensor.bonus_room_brightness
      - sensor.bike_room_brightness
    type: mean
    round_digits: 1
