binary_sensor:
  - platform: template
    sensors:
      ryan_home:
        friendly_name: 'Ryan Home'
        device_class: presence
        value_template: >
          {% if is_state('device_tracker.ryan_phone', 'home') %}
           True
          {% elif is_state('device_tracker.ryanphonenmap', 'home') %}
           True
          {% else %}
           False
          {% endif %}
      chelsea_home:
        friendly_name: 'Chelsea Home'
        device_class: presence
        value_template: >
          {% if is_state('device_tracker.chelsea_phone', 'home') %}
           True
          {% elif is_state('device_tracker.chelseaphonenmap', 'home') %}
           True
          {% else %}
           False
          {% endif %}
      everybody_home:
        friendly_name: 'Everybody Home'
        device_class: presence
        value_template: >
          {% if is_state('binary_sensor.ryan_home', 'on')
             and is_state('binary_sensor.chelsea_home', 'on') %}
           True
           {% else %}
           False
           {% endif %}
      everybody_home_or_distant:
        friendly_name: 'Everybody Home or Distant'
        device_class: presence
        value_template: >
          {% if is_state('binary_sensor.everybody_home', 'on') %}
          True
          {% elif is_state('binary_sensor.ryan_home', 'on')
            and (states('sensor.chelsea_distance_from_home') | float > 3) %}
          True
          {% elif is_state('binary_sensor.chelsea_home', 'on')
            and (states('sensor.ryan_distance_from_home') | float > 3) %}
          True
          {% elif (states('sensor.chelsea_distance_from_home') | float > 3)
            and (states('sensor.ryan_distance_from_home') | float > 3)  %}
          True
          {% else %}
          False
          {% endif %}
