automation:
  - id: living_room_window_open_ok
    alias: 'Living Room: OK to open window'
    trigger:
      - platform: state
        entity_id: climate.living_room_fan
        to: 'cool'
    action:
      - service: light.turn_on
        data:
          entity_id: light.living_room_led
          color_name: green
          brightness: 100

  - id: living_room_window_open_nok
    #initial_state: 'off' #Disabled for winter.
    alias: 'Living Room: Close Windows'
    trigger:
      - platform: state
        entity_id: climate.living_room_fan
        to: 'off'
    action:
      - service: light.turn_on
        data:
          entity_id: light.living_room_led
          color_name: red
          brightness: 100



  - id: lights_left_on
    alias: 'Notification Light: Lights Left On'
    trigger:
      - platform: time
        minutes: '/3'
        seconds: 40
      - platform: state
        entity_id: group.indoor_lights
        to: 'on'
      - platform: state
        entity_id: remote.living_room
        to: 'on'
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: group.indoor_lights
          state: 'on'
        - condition: state
          entity_id: remote.living_room
          state: 'on'
    action:
      - service: light.turn_on
        data:
          entity_id: light.master_bedroom_led
          color_name: white
          brightness: 32
          transition: 10

  - id: lights_turned_off
    alias: 'Notification Light: Lights Turned Off'
    trigger:
      - platform: time
        minutes: '/3'
        seconds: 50
      - platform: state
        entity_id: group.indoor_lights
        to: 'off'
      - platform: state
        entity_id: remote.living_room
        to: 'off'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: group.indoor_lights
          state: 'off'
        - condition: state
          entity_id: remote.living_room
          state: 'off'
    action:
      - service: light.turn_off
        data:
          entity_id: light.master_bedroom_led
          transition: 10
