binary_sensor:
  - platform: template
    sensors:
      everybody_home:
        friendly_name: 'Everybody Home'
        device_class: presence
        value_template: >
          {% if is_state('person.ryan', 'home')
             and is_state('person.chelsea', 'home') %}
           True
           {% else %}
           False
           {% endif %}
      everybody_home_or_distant:
        friendly_name: 'Everybody Home or Distant'
        device_class: presence
        value_template: >
          {% if is_state('binary_sensor.everybody_home', 'on') %}
          True
          {% elif is_state('person.ryan', 'home')
            and (states('sensor.chelsea_distance_from_home') | float > 3) %}
          True
          {% elif is_state('person.chelsea', 'home')
            and (states('sensor.ryan_distance_from_home') | float > 3) %}
          True
          {% elif (states('sensor.chelsea_distance_from_home') | float > 3)
            and (states('sensor.ryan_distance_from_home') | float > 3)  %}
          True
          {% else %}
          False
          {% endif %}
