sensor:
  - platform: min_max
    name: "Indoor Humidity"
    entity_ids:
      - sensor.office_humidity
      - sensor.living_room_humidity
      - sensor.master_bedroom_humidity
      - sensor.bonus_room_humidity
    type: mean
    round_digits: 1

  - platform: min_max
    name: "Indoor Temperature"
    entity_ids:
      - sensor.office_temperature
      - sensor.living_room_temperature
      - sensor.master_bedroom_temperature
      - sensor.bonus_room_temperature
      - sensor.aqi_sensor_temperature
    type: mean
    round_digits: 1

  - platform: min_max
    name: "Indoor CO₂"
    entity_ids:
      - sensor.aqi_co2
      - sensor.office_co2
    type: mean
    round_digits: 1

  - platform: min_max
    name: "Indoor VOC"
    entity_ids:
      - sensor.aqi_total_volatile_organic_compound
      - sensor.office_voc
    type: mean
    round_digits: 1