#All sensors and similar to do with travel, such as distance.
proximity:
  both_home:
    zone: home
    devices:
      - device_tracker.ryan_phone
      - device_tracker.chelsea_phone
    unit_of_measurement: mi

  ryan_home:
    zone: home
    devices:
      - device_tracker.ryan_phone
    unit_of_measurement: mi

  chelsea_home:
    zone: home
    devices:
      - device_tracker.chelsea_phone
    unit_of_measurement: mi

  ryan_work:
    zone: !secret work_1_name
    devices:
      - device_tracker.ryan_phone
    unit_of_measurement: mi

  chelsea_work:
    zone: !secret work_2_name
    devices:
      - device_tracker.chelsea_phone
    unit_of_measurement: mi



binary_sensor:
  - platform: trend
    sensors:
      ryan_headed_home:
        friendly_name: "Ryan Headed Home"
        entity_id: sensor.ryan_distance_from_home
        max_samples: 5
        sample_duration: 900
        device_class: moving
      chelsea_headed_home:
        friendly_name: "Chelsea Headed Home"
        entity_id: sensor.chelsea_distance_from_home
        max_samples: 5
        sample_duration: 900
        device_class: moving
      chelsea_headed_to_ryan:
        friendly_name: "Chelsea Headed to Ryan"
        entity_id: sensor.ryan_chelsea_distance
        max_samples: 5
        sample_duration: 900
        device_class: moving




sensor:
  - platform: template
    sensors:
      ryan_distance_from_home:
        friendly_name: 'Ryan Distance from Home'
        value_template: '{{distance(states.zone.home,states.device_tracker.ryan_phone) | float | round(2) }}'
        unit_of_measurement: 'mi'
      chelsea_distance_from_home:
        friendly_name: 'Chelsea Distance from Home'
        value_template: '{{distance(states.zone.home,states.device_tracker.chelsea_phone) | float | round(2)}}'
        unit_of_measurement: 'mi'
      ryan_chelsea_distance:
        friendly_name: 'Chelsea Distance from Ryan'
        value_template: '{{distance(states.device_tracker.chelsea_phone,states.device_tracker.ryan_phone) | float | round(2)}}'
        unit_of_measurement: 'mi'

  - platform: template
    sensors:
      ryan_homebound_speed:
        friendly_name: "Ryan to Home Speed"
        unit_of_measurement: "MPH"
        value_template: "{{ ((states.binary_sensor.ryan_headed_home.attributes.gradient | float) * 3600) | round(0) }}"
      chelsea_homebound_speed:
        friendly_name: "Chelsea to Home Speed"
        unit_of_measurement: "MPH"
        value_template: "{{ ((states.binary_sensor.chelsea_headed_home.attributes.gradient | float) * 3600) | round(0) }}"
      ryan_chelsea_speed:
        friendly_name: "Chelsea to Ryan Speed"
        unit_of_measurement: "MPH"
        value_template: "{{ ((states.binary_sensor.chelsea_headed_to_ryan.attributes.gradient | float) * 3600) | round(0) }}"

  #I only made one bike sensor because it'll USUALLY be pretty same both ways.
  - platform: google_travel_time
    name: "Chelsea to Ryan Bike Time"
    api_key: !secret google_api_key
    origin: device_tracker.chelsea_phone
    destination: device_tracker.ryan_phone
    options:
      mode: bicycling
    scan_interval: 900

  - platform: google_travel_time
    name: "Ryan to Home Bike Time"
    api_key: !secret google_api_key
    origin: device_tracker.ryan_phone
    destination: zone.home
    options:
      mode: bicycling
    scan_interval: 900

  - platform: google_travel_time
    name: "Chelsea to Home Bike Time"
    api_key: !secret google_api_key
    origin: device_tracker.chelsea_phone
    destination: zone.home
    options:
      mode: bicycling
    scan_interval: 900

  - platform: waze_travel_time
    origin: device_tracker.ryan_phone
    destination: zone.home
    region: 'US'
    name: "Ryan to Home Drive Time"

  - platform: waze_travel_time
    origin: device_tracker.chelsea_phone
    destination: zone.home
    region: 'US'
    name: "Chelsea to Home Drive Time"

  - platform: waze_travel_time
    origin: device_tracker.chelsea_phone
    destination: device_tracker.ryan_phone
    region: 'US'
    name: "Chelsea to Ryan Drive Time"

  - platform: waze_travel_time
    origin: device_tracker.ryan_phone
    destination: device_tracker.chelsea_phone
    region: 'US'
    name: "Ryan to Chelsea Drive Time"
