#Components that facilitate the house "greeting" you.

automation:
  - id: porch_light_off_at_midnight
    alias: "Porch: Turn the Light Off  at Midnight"
    trigger:
      - platform: state
        entity_id: binary_sensor.everybody_home_or_distant
        to: 'on'
        for: '00:10:00'
      - platform: state
        entity_id: input_boolean.guest_mode
        to: 'off'
      - platform: time
        at: '00:00:00'
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
      - condition: state
        entity_id: binary_sensor.everybody_home_or_distant
        state: 'on'
      - condition: time
        before: '04:00:00'
    action:
      - service: light.turn_off
        data:
          entity_id: light.front_porch_light

  - id: porch_light_on_at_sunset
    alias: "Porch: Turn the Light On At Sunset"
    trigger:
      - platform: sun
        event: sunset
        offset: '-00:30:00'
    action:
      - service: light.turn_on
        data:
          entity_id: light.front_porch_light
          brightness: 255

  - id: porch_light_off_at_sunrise
    alias: "Porch: Turn the Light Off At Sunrise"
    trigger:
      - platform: sun
        event: sunrise
        offset: '00:30:00'
    condition:
      condition: state
      entity_id: light.front_porch_light
      state: 'on'
      for: '00:10:00'
    action:
      - service: light.turn_off
        data:
          entity_id: light.front_porch_light
