binary_sensor:
  - platform: ping
    host: 192.168.1.1
    name: Gateway Ping

  - platform: ping
    host: 192.168.100.1
    name: Modem Ping

sensor:
  - platform: template
    sensors:
      ryan_phone_battery:
        friendly_name: "Ryan Phone Battery"
        value_template: "{{ state_attr('device_tracker.ryanphoneapp','battery_level') }}"
        unit_of_measurement: '%'
        device_class: battery

  - platform: template
    sensors:
      chelsea_phone_battery:
        friendly_name: "Chelsea Phone Battery"
        value_template: "{{ state_attr('device_tracker.chelseaphoneapp','battery_level') }}"
        unit_of_measurement: '%'
        device_class: battery
