input_boolean:
  guest_mode:
    name: 'Guest Mode'
    icon: mdi:glass-flute

automation:
  #Guest mode autoenables if there are guests at the house.
  #There are some conditions:
  #Only enables between 8AM and 10PM
  #Only enables if it hasn't been on in 8 hours (prevent reactivation)
  - id: guest_mode_autoenable
    alias: "Guest Mode: Autodetect On"
    trigger:
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: group.guests
        to: 'home'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: group.guests
          state: 'home'
        - condition: state
          entity_id: input_boolean.guest_mode
          state: 'off'
          for:
            hours: 8
        - condition: time
          after: '08:00:00'
          before: '22:00:00'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.guest_mode
      - service: notify.push_main
        data:
          title: 'Party Time'
          message: "Guest Mode has been turned on. If this was wrong, press the 'turn off' button."
          data:
            tag: 'guest_mode_turn_off'
            actions:
            - action: guest_mode_off
              title: "Turn Off"

  #By default, guest mode autodisables if there are no remaining guests at midnight.
  - id: guest_mode_autodisable
    alias: 'Guest Mode: Autodisable'
    trigger:
      - platform: time
        at: '00:00:00'
    condition:
      - condition: state
        entity_id: group.guests
        state: 'not_home'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.guest_mode

  #When all guests are detected to have left, we send a notification to users to ask if GM should be turned off.
  - id: guest_mode_autodisable_prompt
    alias: 'Guest Mode: Autodisable Prompt'
    trigger:
      - platform: state
        entity_id: group.guests
        to: 'not_home'
        for: 00:30:00
    condition:
      condition: state
      entity_id: input_boolean.guest_mode
      state: 'on'
    action:
    - service: notify.push_main
      data:
        title: 'End the Party?'
        message: "All guests were detected to have left. Disable Guest Mode?"
        data:
          tag: 'guest_mode_turn_off'
          actions:
          - action: guest_mode_off
            title: "Turn Off"

  #If a user clicks the notification from guest_mode_autodisable_prompt, turn off the mode.
  - id: guest_mode_notification_callback
    alias: 'Guest Mode: Notification Clicked: Turn Off'
    trigger:
      platform: event
      event_type: html5_notification.clicked
      event_data:
        action: guest_mode_off
    action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.guest_mode

  #When guest mode is activated, turn on the porch light conditionally.
  - id: guest_mode_porch_light_on
    alias: "Guest Mode: Enable Porch Light"
    trigger:
      - platform: state
        entity_id: input_boolean.guest_mode
        to: 'on'
      - platform: sun
        event: sunset
        offset: '-00:30:00'
    condition:
      condition: and
      conditions:
        - condition: sun
          after: sunset
          after_offset: '-00:30:00'
        - condition: time
          before: '23:59:59'
        - condition: state
          entity_id: input_boolean.guest_mode
          state: 'on'
    action:
      - service: light.turn_on
        data:
          entity_id: light.front_porch_light
          brightness: 255

  #When guest mode is activated, turn on the entertaining scene unconditionally.
  - id: guest_mode_activate_scene
    alias: "Guest Mode: Activate Scene"
    trigger:
      - platform: state
        entity_id: input_boolean.guest_mode
        to: 'on'
    action:
      - service: scene.turn_on
        entity_id: scene.entertaining
