august:
  login_method: email
  username: !secret august_username
  password: !secret august_password

scene:
  #Used for the exit button near the front door - arms the door lock to trigger the next time the door closes.
  - name: 'Front Door Exit'
    entities:
      scene.indoor_off: on
      automation.lock_front_door_next_close: on

automation:
  - id: lock_front_door_next_close
    #Lock the front door immediately the next time it is closed.
    alias: 'Front Door Lock: Lock immediately on next close'
    initial_state: 'off'
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door_open
        from: 'on'
        to: 'off'
    action:
      - service: lock.lock
        entity_id: lock.front_door
      - service: automation.turn_off
        entity_id: automation.lock_front_door_next_close
