input_datetime:
  sunrise_alarm_weekday:
    name: Weekday
    has_date: False
    has_time: True
  sunrise_alarm_weekend:
    name: Weekend
    has_date: False
    has_time: True

input_number:
  sunrise_alarm_fade_time:
    name: Fade Time (Minutes)
    icon: mdi:timelapse
    min: 15
    max: 90
    step: 5

  sunrise_alarm_max_level:
    name: Light Level
    icon: mdi:lightbulb-on-outline
    min: 0
    max: 100
    step: 5

script:
  sunrise_alarm_light_on:
    alias: 'Sunrise Alarm: Turn On Light'
    sequence:
    - service: light.turn_on
      data_template:
        entity_id: light.master_bathroom_vanity_lights
        transition: "{{ states('input_number.sunrise_alarm_fade_time') | float * 60 | int }}"
        brightness_pct: "{{ states('input_number.sunrise_alarm_max_level') | round(0) | int }}"

automation:
  - id: sunrise_alarm_bedroom
    alias: "Bedroom Sunrise Alarm"
    trigger:
      - platform: time_pattern
        minutes: '*'
        seconds: 50
    condition:
      condition: and
      conditions:
        - condition: or
          conditions:
            - condition: and
              conditions:
                - condition: state
                  entity_id: binary_sensor.workday_sensor
                  state: 'on'
                - condition: template
                  value_template: "{{ (now().hour | int) == (states.input_datetime.sunrise_alarm_weekday.attributes.hour) and (now().minute | int) == (states.input_datetime.sunrise_alarm_weekday.attributes.minute) }}"
            - condition: and
              conditions:
                - condition: state
                  entity_id: binary_sensor.workday_sensor
                  state: 'off'
                - condition: template
                  value_template: "{{ (now().hour | int) == (states.input_datetime.sunrise_alarm_weekend.attributes.hour) and (now().minute | int) == (states.input_datetime.sunrise_alarm_weekend.attributes.minute) }}"
        - condition: state
          entity_id: binary_sensor.anybody_home
          state: 'on'
    action:
    - service: script.turn_on
      entity_id: script.sunrise_alarm_light_on
