input_datetime:
  sunrise_alarm_weekday:
    name: Weekday
    has_date: False
    has_time: True
  sunrise_alarm_weekend:
    name: Weekend
    has_date: False
    has_time: True

input_number:
  sunrise_alarm_fade_time:
    name: Fade Time (Minutes)
    icon: mdi:timelapse
    min: 1
    max: 60
    step: 1

  sunrise_alarm_max_level:
    name: Light Level
    icon: mdi:lightbulb-on-outline
    min: 0
    max: 100
    step: 1

input_boolean:
  sunrise_alarm_armed:
    name: 'Enabled'
    icon: mdi:alarm

script:
  sunrise_alarm_light_on:
    alias: 'Sunrise Alarm: Turn On Light'
    sequence:
    - service: automation.turn_off
      data:
        entity_id: automation.master_bedroom_turn_on_nightstand_lamp
    - wait_template: "{{ is_state('automation.master_bedroom_turn_on_nightstand_lamp','off') }}"
      timeout: '00:01:00'
    - service: light.turn_on
      data_template:
        entity_id: light.master_bedroom_sconce
        transition: "{{ states('input_number.sunrise_alarm_fade_time') | float * 60 | int }}"
        brightness_pct: "{{ states('input_number.sunrise_alarm_max_level') | round(0) | int }}"
    - wait_template: "{{ is_state('light.master_bedroom_sconce','on') }}"
      timeout: '00:01:00'
    - service: automation.turn_on
      data:
        entity_id: automation.master_bedroom_turn_on_nightstand_lamp

automation:
  - id: sunrise_alarm_bedroom
    alias: "Bedroom Sunrise Alarm"
    trigger:
      - platform: time
        minutes: '/1'
        seconds: 50
    condition:
      condition: and
      conditions:
        - condition: or
          conditions:
            - condition: and
              conditions:
                - condition: state
                  entity_id: binary_sensor.workday_sensor
                  state: 'on'
                - condition: template
                  value_template: "{{ (now().hour | int) == (states.input_datetime.sunrise_alarm_weekday.attributes.hour) and (now().minute | int) == (states.input_datetime.sunrise_alarm_weekday.attributes.minute) }}"
            - condition: and
              conditions:
                - condition: state
                  entity_id: binary_sensor.workday_sensor
                  state: 'off'
                - condition: template
                  value_template: "{{ (now().hour | int) == (states.input_datetime.sunrise_alarm_weekend.attributes.hour) and (now().minute | int) == (states.input_datetime.sunrise_alarm_weekend.attributes.minute) }}"
        - condition: state
          entity_id: group.all_devices
          state: 'home'
        - condition: state
          entity_id: input_boolean.sunrise_alarm_armed
          state: 'on'
    action:
    - service: script.turn_on
      entity_id: script.sunrise_alarm_light_on
