input_datetime:
  sunrise_alarm_weekday:
    name: Weekday
    has_date: False
    has_time: True
  sunrise_alarm_weekend:
    name: Weekend
    has_date: False
    has_time: True

input_number:
  sunrise_alarm_fade_time:
    name: Fade Time (Minutes)
    icon: mdi:timelapse
    min: 15
    max: 90
    step: 5

  sunrise_alarm_max_level:
    name: Light Level
    icon: mdi:lightbulb-on-outline
    min: 0
    max: 100
    step: 5

script:
  sunrise_alarm_light_on:
    alias: 'Sunrise Alarm: Turn On Light'
    sequence:
    - service: light.turn_on
      data:
        entity_id: light.master_bathroom_vanity_lights
        transition: "{{ states('input_number.sunrise_alarm_fade_time') | float * 60 | int }}"
        brightness_pct: "{{ states('input_number.sunrise_alarm_max_level') | round(0) | int }}"

automation:
  - id: sunrise_alarm_bedroom_weekday
    alias: "Bedroom Sunrise Alarm Weekday"
    trigger:
      - platform: time
        at: input_datetime.sunrise_alarm_weekday
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: binary_sensor.anybody_home
        state: 'on'
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'on'
    action:
    - service: script.turn_on
      entity_id: script.sunrise_alarm_light_on

  - id: sunrise_alarm_bedroom_weekend
    alias: "Bedroom Sunrise Alarm Weekend"
    trigger:
      - platform: time
        at: input_datetime.sunrise_alarm_weekend
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: binary_sensor.anybody_home
        state: 'on'
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'off'
    action:
    - service: script.turn_on
      entity_id: script.sunrise_alarm_light_on